:_mod-docs-content-type: ASSEMBLY
[id="persistent-storage-using-azure"]
= Persistent storage using Azure
include::../includes/common-attributes.adoc[]
:context: persistent-storage-azure


{product-title} supports Microsoft Azure Disk volumes. You can
provision your {product-title} cluster with persistent storage using Azure.
Some familiarity with Kubernetes and Azure is assumed.
The Kubernetes persistent volume framework allows administrators to provision a
cluster with persistent storage and gives users a way to request those
resources without having any knowledge of the underlying infrastructure.
Azure Disk volumes can be provisioned dynamically.
Persistent volumes are not bound to a single project or namespace; they can be
shared across the {product-title} cluster.
Persistent volume claims are specific to a project or namespace and can be
requested by users.

[IMPORTANT]
====
{product-title} defaults to using an in-tree (non-CSI) plugin to provision Azure Disk storage.

In future {product-title} versions, volumes provisioned using existing in-tree plugins are planned for migration to their equivalent CSI driver. CSI automatic migration should be seamless. Migration does not change how you use all existing API objects, such as persistent volumes, persistent volume claims, and storage classes. For more information about migration, see xref:persistent-storage-csi-migration[CSI automatic migration].

After full migration, in-tree plugins will eventually be removed in future versions of {product-title}.
====

[IMPORTANT]
====
High availability of storage in the infrastructure is left to the underlying
storage provider.
====

[role="_additional-resources"]
.Additional resources

* link:https://azure.microsoft.com/en-us/services/storage/disks[Microsoft Azure Disk]

include::../includes/storage-azure-create-storage-class.adoc[leveloffset=+1]

include::../includes/storage-persistent-storage-creating-volume-claim.adoc[leveloffset=+1]

include::../includes/storage-persistent-storage-azure-volume-format.adoc[leveloffset=+1]

//Machine sets that deploy machines on ultra disks using PVCs
include::../includes/machineset-azure-ultra-disk.adoc[leveloffset=+1]

[role="_additional-resources"]
.Additional resources
* link:https://docs.microsoft.com/en-us/azure/virtual-machines/disks-types#ultra-disks[Microsoft Azure ultra disks documentation]
* xref:machineset-azure-ultra-disk_persistent-storage-csi-azure[Machine sets that deploy machines on ultra disks using CSI PVCs]
* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/machine_management/#machineset-azure-ultra-disk_creating-machineset-azure[Machine sets that deploy machines on ultra disks as data disks]

//Creating machines on ultra disks by using compute machine sets
include::../includes/machineset-creating-azure-ultra-disk.adoc[leveloffset=+2]

//Troubleshooting resources for compute machine sets that enable ultra disks
include::../includes/machineset-troubleshooting-azure-ultra-disk.adoc[leveloffset=+2]
