:_mod-docs-content-type: ASSEMBLY
:context: creating-multi-arch-compute-nodes-ibm-z
[id="creating-multi-arch-compute-nodes-ibm-z"]
= Creating a cluster with multi-architecture compute machines on {ibm-z-title} and {ibm-linuxone-title} with z/VM
include::../includes/common-attributes.adoc[]


To create a cluster with multi-architecture compute machines on {ibm-z-name} and {ibm-linuxone-name} (`s390x`) with z/VM, you must have an existing single-architecture `x86_64` cluster. You can then add `s390x` compute machines to your {product-title} cluster.

Before you can add `s390x` nodes to your cluster, you must upgrade your cluster to one that uses the multi-architecture payload. For more information on migrating to the multi-architecture payload, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/updating_clusters/#migrating-to-multi-payload[Migrating to a cluster with multi-architecture compute machines].

The following procedures explain how to create a {op-system} compute machine using a z/VM instance. This will allow you to add `s390x` nodes to your cluster and deploy a cluster with multi-architecture compute machines.

include::../includes/multi-architecture-verifying-cluster-compatibility.adoc[leveloffset=+1]

include::../includes/machine-user-infra-machines-ibm-z.adoc[leveloffset=+1]

include::../includes/installation-approve-csrs.adoc[leveloffset=+1]