:_mod-docs-content-type: ASSEMBLY
:context: creating-multi-arch-compute-nodes-ibm-power
[id="creating-multi-arch-compute-nodes-ibm-power"]
= Creating a cluster with multi-architecture compute machines on {ibm-power-title}
include::../includes/common-attributes.adoc[]


To create a cluster with multi-architecture compute machines on {ibm-power-name} (`ppc64le`), you must have an existing single-architecture (`x86_64`) cluster. You can then add `ppc64le` compute machines to your {product-title} cluster.

[IMPORTANT]
====
Before you can add `ppc64le` nodes to your cluster, you must upgrade your cluster to one that uses the multi-architecture payload. For more information on migrating to the multi-architecture payload, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/updating_clusters/#migrating-to-multi-payload[Migrating to a cluster with multi-architecture compute machines].
====

The following procedures explain how to create a {op-system} compute machine using an ISO image or network PXE booting. This will allow you to add `ppc64le` nodes to your cluster and deploy a cluster with multi-architecture compute machines.

include::../includes/multi-architecture-verifying-cluster-compatibility.adoc[leveloffset=+1]

include::../includes/machine-user-infra-machines-iso.adoc[leveloffset=+1]

include::../includes/machine-user-infra-machines-pxe.adoc[leveloffset=+1]

include::../includes/installation-approve-csrs.adoc[leveloffset=+1]