:_mod-docs-content-type: ASSEMBLY
:context: creating-multi-arch-compute-nodes-bare-metal
[id="creating-multi-arch-compute-nodes-bare-metal"]
= Creating a cluster with multi-architecture compute machine on bare metal
include::../includes/common-attributes.adoc[]


To create a cluster with multi-architecture compute machines on bare metal, you must have an existing single-architecture bare metal cluster. For more information on bare metal installations, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/installing/#installing-bare-metal[Installing a user provisioned cluster on bare metal]. You can then add 64-bit ARM compute machines to your {product-title} cluster on bare metal.

Before you can add 64-bit ARM nodes to your bare metal cluster, you must upgrade your cluster to one that uses the multi-architecture payload. For more information on migrating to the multi-architecture payload, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/updating_clusters/#migrating-to-multi-payload[Migrating to a cluster with multi-architecture compute machines].

The following procedures explain how to create a {op-system} compute machine using an ISO image or network PXE booting. This will allow you to add ARM64 nodes to your bare metal cluster and deploy a cluster with multi-architecture compute machines.

include::../includes/multi-architecture-verifying-cluster-compatibility.adoc[leveloffset=+1]

include::../includes/machine-user-infra-machines-iso.adoc[leveloffset=+1]

include::../includes/machine-user-infra-machines-pxe.adoc[leveloffset=+1]

include::../includes/installation-approve-csrs.adoc[leveloffset=+1]