:_mod-docs-content-type: ASSEMBLY
[id="about-installing-oadp"]
= About installing OADP
include::../../includes/common-attributes.adoc[]
:context: about-installing-oadp


As a cluster administrator, you install the OpenShift API for Data Protection (OADP) by installing the OADP Operator. The OADP Operator installs link:https://{velero-domain}/docs/v{velero-version}/[Velero {velero-version}].

include::../../includes/oadp-mtc-operator.adoc[]

To back up Kubernetes resources and internal images, you must have object storage as a backup location, such as one of the following storage types:

* xref:installing-oadp-aws[Amazon Web Services]
* xref:installing-oadp-azure[Microsoft Azure]
* xref:installing-oadp-gcp[Google Cloud Platform]
* xref:installing-oadp-mcg[Multicloud Object Gateway]
* AWS S3 compatible object storage, such as Multicloud Object Gateway or MinIO

:FeatureName: The `CloudStorage` API, which automates the creation of a bucket for object storage,
include::../../includes/technology-preview.adoc[]

[NOTE]
====
The `CloudStorage` API is a Technology Preview feature when you use a `CloudStorage` object and want OADP to use the `CloudStorage` API to automatically create an S3 bucket for use as a `BackupStorageLocation`.

The `CloudStorage` API supports manually creating a `BackupStorageLocation` object by specifying an existing S3 bucket. The `CloudStorage` API that creates an S3 bucket automatically is currently only enabled for AWS S3 storage.
====

You can back up persistent volumes (PVs) by using snapshots or a File System Backup (FSB).

To back up PVs with snapshots, you must have a cloud provider that supports either a native snapshot API or Container Storage Interface (CSI) snapshots, such as one of the following cloud providers:

* xref:installing-oadp-aws[Amazon Web Services]
* xref:installing-oadp-azure[Microsoft Azure]
* xref:installing-oadp-gcp[Google Cloud Platform]
* CSI snapshot-enabled cloud provider, such as xref:installing-oadp-ocs[OpenShift Data Foundation]

include::../../includes/oadp-ocp-compat.adoc[]

If your cloud provider does not support snapshots or if your storage is NFS, you can back up applications with xref:backing-up-applications[Backing up applications with File System Backup: Kopia or Restic] on object storage.

You create a default `Secret` and then you install the Data Protection Application.

include::../../includes/oadp-s3-compatible-backup-storage-providers.adoc[leveloffset=+1]

include::../../includes/oadp-configuring-noobaa-for-dr.adoc[leveloffset=+1]

[discrete]
[role="_additional-resources"]
.Additional resources

* link:https://{velero-domain}/docs/v{velero-version}/locations/[Overview of backup and snapshot locations in the Velero documentation]

include::../../includes/about-oadp-update-channels.adoc[leveloffset=+1]
include::../../includes/about-installing-oadp-on-multiple-namespaces.adoc[leveloffset=+1]

[role="_additional-resources"]
.Additional resources

* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/operators/#olm-csv_olm-understanding-olm[Cluster service version]

include::../../includes/oadp-velero-cpu-memory-requirements.adoc[leveloffset=+1]
include::../../includes/oadp-backup-restore-for-large-usage.adoc[leveloffset=+2]