:_mod-docs-content-type: ASSEMBLY
[id="installing-oadp-mcg"]
= Configuring the OpenShift API for Data Protection with Multicloud Object Gateway
include::../../includes/common-attributes.adoc[]
:context: installing-oadp-mcg
:installing-oadp-mcg:
:credentials: cloud-credentials
:provider: aws


You install the OpenShift API for Data Protection (OADP) with Multicloud Object Gateway (MCG) by installing the OADP Operator. The Operator installs link:https://{velero-domain}/docs/v{velero-version}/[Velero {velero-version}].

include::../../includes/oadp-mtc-operator.adoc[]

You configure xref:installing-oadp-mcg[Multicloud Object Gateway] as a backup location.
MCG is a component of {rh-storage}. You configure MCG as a backup location in the `DataProtectionApplication` custom resource (CR).

:FeatureName: The `CloudStorage` API, which automates the creation of a bucket for object storage,
include::../../includes/technology-preview.adoc[]

You create a `Secret` for the backup location and then you install the Data Protection Application. For more details, see xref:oadp-installing-operator-doc[Installing the OADP Operator].

To install the OADP Operator in a restricted network environment, you must first disable the default OperatorHub sources and mirror the Operator catalog. For details, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/operators/#olm-restricted-networks[Using Operator Lifecycle Manager on restricted networks].

//include::../../includes/oadp-installing-operator.adoc[leveloffset=+1]
include::../../includes/migration-configuring-mcg.adoc[leveloffset=+1]
include::../../includes/oadp-about-backup-snapshot-locations-secrets.adoc[leveloffset=+1]
include::../../includes/oadp-creating-default-secret.adoc[leveloffset=+2]
include::../../includes/oadp-secrets-for-different-credentials.adoc[leveloffset=+2]

[id="configuring-dpa-mcg"]
== Configuring the Data Protection Application

You can configure the Data Protection Application by setting Velero resource allocations or enabling self-signed CA certificates.

include::../../includes/oadp-setting-resource-limits-and-requests.adoc[leveloffset=+2]
include::../../includes/oadp-self-signed-certificate.adoc[leveloffset=+2]

include::../../includes/oadp-installing-dpa-1-2-and-earlier.adoc[leveloffset=+1]
include::../../includes/oadp-installing-dpa-1-3.adoc[leveloffset=+1]
include::../../includes/oadp-enabling-csi-dpa.adoc[leveloffset=+2]

:installing-oadp-mcg!:
