:_mod-docs-content-type: ASSEMBLY
[id="cco-mode-manual"]
= Manual mode with long-term credentials for components
include::../includes/common-attributes.adoc[]
:context: cco-mode-manual


Manual mode is supported for Alibaba Cloud, Amazon Web Services (AWS), global Microsoft Azure, Microsoft Azure Stack Hub, Google Cloud Platform (GCP), {ibm-cloud-name}, and Nutanix.

[id="manual-mode-classic_{context}"]
== User-managed credentials

In manual mode, a user manages cloud credentials instead of the Cloud Credential Operator (CCO). To use this mode, you must examine the `CredentialsRequest` CRs in the release image for the version of {product-title} that you are running or installing, create corresponding credentials in the underlying cloud provider, and create Kubernetes Secrets in the correct namespaces to satisfy all `CredentialsRequest` CRs for the cluster's cloud provider. Some platforms use the CCO utility (`ccoctl`) to facilitate this process during installation and updates.

Using manual mode with long-term credentials allows each cluster component to have only the permissions it requires, without storing an administrator-level credential in the cluster. This mode also does not require connectivity to services such as the AWS public IAM endpoint. However, you must manually reconcile permissions with new release images for every upgrade.

For information about configuring your cloud provider to use manual mode, see the manual credentials management options for your cloud provider.

[NOTE]
====
An AWS, global Azure, or GCP cluster that uses manual mode might be configured to use short-term credentials for different components. For more information, see xref:cco-short-term-creds[Manual mode with short-term credentials for components].
====

[role="_additional-resources"]
[id="additional-resources_cco-mode-manual"]
== Additional resources

* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/installing/#manually-creating-alibaba-ram[Manually creating RAM resources for Alibaba Cloud]
* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/installing/#manually-create-iam_installing-aws-customizations[Manually creating long-term credentials for AWS]
* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/installing/#manually-create-iam_installing-azure-customizations[Manually creating long-term credentials for Azure]
* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/installing/#manually-create-iam_installing-gcp-customizations[Manually creating long-term credentials for GCP]
* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/installing/#configuring-iam-ibm-cloud[Configuring IAM for {ibm-cloud-name}]
* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/installing/#manually-create-iam-nutanix_installing-nutanix-installer-provisioned[Configuring IAM for Nutanix]
* xref:cco-short-term-creds[Manual mode with short-term credentials for components]
* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/updating_clusters/#preparing-manual-creds-update[Preparing to update a cluster with manually maintained credentials]