:_mod-docs-content-type: ASSEMBLY
[id="configuring-network-observability-operators"]
= Configuring the Network Observability Operator
include::includes/common-attributes.adoc[]
:context: network_observability


You can update the Flow Collector API resource to configure the Network Observability Operator and its managed components. The  Flow Collector is explicitly created during installation. Since this resource operates cluster-wide, only a single `FlowCollector` is allowed, and it has to be named `cluster`.


include::includes/network-observability-flowcollector-view.adoc[leveloffset=+1]

[role="_additional-resources"]
.Additional resources
For more information about conversation tracking, see xref:network-observability-working-with-conversations_nw-observe-network-traffic[Working with conversations].

include::includes/network-observability-flowcollector-kafka-config.adoc[leveloffset=+1]
include::includes/network-observability-enriched-flows.adoc[leveloffset=+1]

[role="_additional-resources"]
.Additional resources
For more information about specifying flow format, see xref:network-observability-flows-format_json_reference[Network flows format reference].

include::includes/network-observability-configuring-FLP-sampling.adoc[leveloffset=+1]
include::includes/network-observability-configuring-quickfilters-flowcollector.adoc[leveloffset=+1]
include::includes/network-observability-SRIOV-configuration.adoc[leveloffset=+1]
[role="_additional-resources"]
.Additional resources
For more information about creating the `SriovNetwork` custom resource, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/networking/#cnf-creating-an-additional-sriov-network-with-vrf-plug-in_configuring-sriov-device[Creating an additional SR-IOV network attachment with the CNI VRF plugin].

include::includes/network-observability-resource-recommendations.adoc[leveloffset=+1]
include::includes/network-observability-resources-table.adoc[leveloffset=+2]