:_mod-docs-content-type: ASSEMBLY
[id="ipi-vsphere-preparing-to-install"]
= Preparing to install a cluster using installer-provisioned infrastructure
include::../../includes/common-attributes.adoc[]
:context: ipi-vsphere-preparing-to-install


You prepare to install an {product-title} cluster on vSphere by completing the following steps:

* Downloading the installation program.
+
[NOTE]
====
If you are installing in a disconnected environment, you extract the installation program from the mirrored content. For more information, see xref:installing-mirroring-installation-images[Mirroring images for a disconnected installation].
====
* Installing the {oc-first}.
+
[NOTE]
====
If you are installing in a disconnected environment, install `oc` to the mirror host.
====
* Generating an SSH key pair. You can use this key pair to authenticate into the {product-title} cluster's nodes after it is deployed.
* Adding your vCenter’s trusted root CA certificates to your system trust.

include::../../includes/installation-obtaining-installer.adoc[leveloffset=+1]

include::../../includes/cli-installing-cli.adoc[leveloffset=+1]

include::../../includes/ssh-agent-using.adoc[leveloffset=+1]

include::../../includes/installation-adding-vcenter-root-certificates.adoc[leveloffset=+1]
