:_mod-docs-content-type: ASSEMBLY
[id="virt-post-install-network-config"]
= Postinstallation network configuration
include::../includes/common-attributes.adoc[]
:context: virt-post-install-network-config


By default, {VirtProductName} is installed with a single, internal pod network.

After you install {VirtProductName}, you can install networking Operators and configure additional networks.

[id="installing-operators"]
== Installing networking Operators

You must install the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/networking/#k8s-nmstate-about-the-k8s-nmstate-operator[Kubernetes NMState Operator] to configure a Linux bridge network for live migration or external access to virtual machines (VMs).

You can install the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/networking/#about-sriov[SR-IOV Operator] to manage SR-IOV network devices and network attachments.

include::../includes/k8s-nmstate-installing-the-kubernetes-nmstate-operator.adoc[leveloffset=+2]

include::../includes/nw-sriov-installing-operator.adoc[leveloffset=+2]

[id="configuring-linux-bridge-network"]
== Configuring a Linux bridge network

After you install the Kubernetes NMState Operator, you can configure a Linux bridge network for live migration or external access to virtual machines (VMs).

include::../includes/virt-creating-linux-bridge-nncp.adoc[leveloffset=+2]

include::../includes/virt-creating-linux-bridge-nad-web.adoc[leveloffset=+2]

[id="next-steps_configuring-linux-bridge-network"]
=== Next steps
* xref:virt-attaching-vm-secondary-network-cli_virt-connecting-vm-to-linux-bridge[Attaching a virtual machine (VM) to a Linux bridge network]

[id="configuring-network-live-migration"]
== Configuring a network for live migration

After you have configured a Linux bridge network, you can configure a dedicated network for live migration. A dedicated network minimizes the effects of network saturation on tenant workloads during live migration.

include::../includes/virt-configuring-secondary-network-vm-live-migration.adoc[leveloffset=+2]

include::../includes/virt-selecting-migration-network-ui.adoc[leveloffset=+2]

[id="configuring-sriov-network"]
== Configuring an SR-IOV network

After you install the SR-IOV Operator, you can configure an SR-IOV network.

include::../includes/nw-sriov-configuring-device.adoc[leveloffset=+2]

include::../includes/nw-sriov-network-attachment.adoc[leveloffset=+2]

[id="next-steps_configuring-sriov-network"]
=== Next steps
* xref:virt-attaching-vm-to-sriov-network_virt-connecting-vm-to-sriov[Attaching a virtual machine (VM) to an SR-IOV network]

include::../includes/virt-enabling-load-balancer-service-web.adoc[leveloffset=+1]
