:_mod-docs-content-type: ASSEMBLY
[id="installing-preparing"]
= Selecting a cluster installation method and preparing it for users
include::includes/common-attributes.adoc[]
:context: installing-preparing


Before you install {product-title}, decide what kind of installation process to follow and verify that you have all of the required resources to prepare the cluster for users.

[id="installing-preparing-selecting-cluster-type"]
== Selecting a cluster installation type
Before you install an {product-title} cluster, you need to select the best installation instructions to follow. Think about your answers to the following questions to select the best option.

[id="installing-preparing-install-manage"]
=== Do you want to install and manage an {product-title} cluster yourself?

If you want to install and manage {product-title} yourself, you can install it on the following platforms:

* Alibaba Cloud
* Amazon Web Services (AWS) on 64-bit x86 instances
ifndef::openshift-origin[]
* Amazon Web Services (AWS) on 64-bit ARM instances
endif::openshift-origin[]
* Microsoft Azure on 64-bit x86 instances
* Microsoft Azure on 64-bit ARM instances
* Microsoft Azure Stack Hub
* Google Cloud Platform (GCP) on 64-bit x86 instances
* Google Cloud Platform (GCP) on 64-bit ARM instances
* {rh-openstack-first}
* {ibm-cloud-name}
* {ibm-z-name} or {ibm-linuxone-name}
* {ibm-z-name} or {ibm-linuxone-name} for {op-system-base-full} KVM
* {ibm-power-name}
* {ibm-power-server-name}
* Nutanix
* VMware vSphere
* Bare metal or other platform agnostic infrastructure
// might want a note about single node here

You can deploy an {product-title} 4 cluster to both on-premise hardware and to cloud hosting services, but all of the machines in a cluster must be in the same data center or cloud hosting service.

If you want to use {product-title} but do not want to manage the cluster yourself, you have several managed service options. If you want a cluster that is fully managed by Red Hat, you can use link:https://www.openshift.com/products/dedicated/[OpenShift Dedicated] or link:https://www.openshift.com/products/online/[OpenShift Online]. You can also use OpenShift as a managed service on Azure, AWS, {ibm-cloud-name}, or Google Cloud. For more information about managed services, see the link:https://www.openshift.com/products[OpenShift Products] page. If you install an {product-title} cluster with a cloud virtual machine as a virtual bare metal, the corresponding cloud-based storage is not supported.

[id="installing-preparing-migrate"]
=== Have you used {product-title} 3 and want to use {product-title} 4?

If you used {product-title} 3 and want to try {product-title} 4, you need to understand how different {product-title} 4 is. {product-title} 4 weaves the Operators that package, deploy, and manage Kubernetes applications and the operating system that the platform runs on, {op-system-first}, together seamlessly. Instead of deploying machines and configuring their operating systems so that you can install {product-title} on them, the {op-system} operating system is an integral part of the {product-title} cluster. Deploying the operating system for the cluster machines is part of the installation process for {product-title}. See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/migrating_from_version_3_to_4/#migration-comparing-ocp-3-4[Differences between {product-title} 3 and 4].

Because you need to provision machines as part of the {product-title} cluster installation process, you cannot upgrade an {product-title} 3 cluster to {product-title} 4. Instead, you must create a new {product-title} 4 cluster and migrate your {product-title} 3 workloads to them. For more information about migrating, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/migrating_from_version_3_to_4/#migration-from-version-3-to-4-overview[Migrating from {product-title} 3 to 4 overview]. Because you must migrate to {product-title} 4, you can use any type of production cluster installation process to create your new cluster.

[id="installing-preparing-existing-components"]
=== Do you want to use existing components in your cluster?

Because the operating system is integral to {product-title}, it is easier to let the installation program for {product-title} stand up all of the infrastructure. These are called _installer provisioned infrastructure_ installations. In this type of installation, you can provide some existing infrastructure to the cluster, but the installation program deploys all of the machines that your cluster initially needs.

You can deploy an installer-provisioned infrastructure cluster without specifying any customizations to the cluster or its underlying machines to xref:installing-alibaba-default[Alibaba Cloud], xref:installing-aws-default[AWS], xref:installing-azure-default[Azure], xref:installing-azure-stack-hub-default[Azure Stack Hub], xref:installing-gcp-default[GCP], xref:installing-nutanix-installer-provisioned[Nutanix].

If you need to perform basic configuration for your installer-provisioned infrastructure cluster, such as the instance type for the cluster machines, you can customize an installation for xref:installing-alibaba-customizations[Alibaba Cloud], xref:installing-aws-customizations[AWS], xref:installing-azure-customizations[Azure], xref:installing-gcp-customizations[GCP], xref:installing-nutanix-installer-provisioned[Nutanix].

For installer-provisioned infrastructure installations, you can use an existing xref:installing-aws-vpc[VPC in AWS], xref:installing-azure-vnet[vNet in Azure], or xref:installing-gcp-vpc[VPC in GCP]. You can also reuse part of your networking infrastructure so that your cluster in xref:installing-aws-network-customizations[AWS], xref:installing-azure-network-customizations[Azure], xref:installing-gcp-network-customizations[GCP] can coexist with existing IP address allocations in your environment and integrate with existing MTU and VXLAN configurations. If you have existing accounts and credentials on these clouds, you can re-use them, but you might need to modify the accounts to have the required permissions to install {product-title} clusters on them.


You can use the installer-provisioned infrastructure method to create appropriate machine instances on your hardware for xref:installing-vsphere-installer-provisioned[vSphere], and xref:../installing/installing_bare_metal_ipi/ipi-install-overview#ipi-install-overview[bare metal]. Additionally, for xref:installing-vsphere-installer-provisioned-network-customizations[vSphere], you can also customize additional network parameters during installation.


If you want to reuse extensive cloud infrastructure, you can complete a _user-provisioned infrastructure_ installation. With these installations, you manually deploy the machines that your cluster requires during the installation process. If you perform a user-provisioned infrastructure installation on xref:installing-aws-user-infra[AWS], xref:installing-azure-user-infra[Azure], xref:installing-azure-stack-hub-user-infra[Azure Stack Hub], you can use the provided templates to help you stand up all of the required components. You can also reuse a shared xref:installing-gcp-user-infra-vpc[VPC on GCP]. Otherwise, you can use the xref:installing-platform-agnostic[provider-agnostic] installation method to deploy a cluster into other clouds.


You can also complete a user-provisioned infrastructure installation on your existing hardware. If you use xref:installing-openstack-user[{rh-openstack}], xref:installing-ibm-z[{ibm-z-name} or {ibm-linuxone-name}], xref:installing-ibm-z-kvm[{ibm-z-name} and {ibm-linuxone-name} with {op-system-base} KVM], xref:installing-ibm-power[{ibm-power-title}], or xref:installing-vsphere[vSphere], use the specific installation instructions to deploy your cluster. If you use other supported hardware, follow the xref:installing-bare-metal[bare metal installation] procedure. For some of these platforms, such as xref:installing-vsphere-network-customizations[vSphere], and xref:installing-bare-metal-network-customizations[bare metal], you can also customize additional network parameters during installation.


[id="installing-preparing-security"]
=== Do you need extra security for your cluster?

If you use a user-provisioned installation method, you can configure a proxy for your cluster. The instructions are included in each installation procedure.

If you want to prevent your cluster on a public cloud from exposing endpoints externally, you can deploy a private cluster with installer-provisioned infrastructure on xref:installing-aws-private[AWS], xref:installing-azure-private[Azure], or xref:installing-gcp-private[GCP].

If you need to install your cluster that has limited access to the internet, such as a disconnected or restricted network cluster, you can xref:installing-mirroring-installation-images[mirror the installation packages] and install the cluster from them. Follow detailed instructions for user provisioned infrastructure installations into restricted networks for xref:installing-restricted-networks-aws[AWS], xref:installing-restricted-networks-gcp[GCP], xref:installing-restricted-networks-ibm-z[{ibm-z-name} or {ibm-linuxone-name}], xref:installing-restricted-networks-ibm-z-kvm[{ibm-z-name} or {ibm-linuxone-name} with {op-system-base} KVM], xref:installing-restricted-networks-ibm-power[{ibm-power-name}], xref:installing-restricted-networks-vsphere[vSphere], or xref:installing-restricted-networks-bare-metal[bare metal]. You can also install a cluster into a restricted network using installer-provisioned infrastructure by following detailed instructions for xref:installing-restricted-networks-aws-installer-provisioned[AWS], xref:installing-restricted-networks-gcp-installer-provisioned[GCP], xref:installing-ibm-cloud-restricted[{ibm-cloud-name}], xref:installing-restricted-networks-nutanix-installer-provisioned[Nutanix], xref:installing-openstack-installer-restricted[{rh-openstack}], and xref:installing-restricted-networks-installer-provisioned-vsphere[vSphere].


If you need to deploy your cluster to an xref:installing-aws-government-region[AWS GovCloud region], xref:installing-aws-china-region[AWS China region], or xref:installing-azure-government-region[Azure government region], you can configure those custom regions during an installer-provisioned infrastructure installation.

ifndef::openshift-origin[]
You can also configure the cluster machines to use the {op-system-base} cryptographic libraries that have been submitted to NIST for xref:installing-fips[FIPS 140-2/140-3 Validation] during installation.

[IMPORTANT]
====
When running {op-system-base-full} or {op-system-first} booted in FIPS mode, {product-title} core components use the {op-system-base} cryptographic libraries that have been submitted to NIST for FIPS 140-2/140-3 Validation on only the x86_64, ppc64le, and s390x architectures.
====

endif::[]

////
[id="installing-preparing-single-node"]
=== Are you installing single-node clusters at the edge?

You can use the assisted installer to deploy xref:../installing/installing_sno/install-sno-installing-sno.adoc#installing-sno[single node] clusters for edge workloads.
////

[id="installing-preparing-cluster-for-users"]
== Preparing your cluster for users after installation

Some configuration is not required to install the cluster but recommended before your users access the cluster. You can customize the cluster itself by link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/postinstallation_configuration/#available_cluster_customizations[customizing] the Operators that make up your cluster and integrate you cluster with other required systems, such as an identity provider.
//This link will change when we consolidate the customizations page with the postinstallation activities.

For a production cluster, you must configure the following integrations:

* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/storage/#understanding-persistent-storage[Persistent storage]
* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/authentication_and_authorization/#understanding-identity-provider[An identity provider]
* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/monitoring/#configuring-the-monitoring-stack[Monitoring core OpenShift Container Platform components]

[id="installing-preparing-cluster-for-workloads"]
== Preparing your cluster for workloads

Depending on your workload needs, you might need to take extra steps before you begin deploying applications. For example, after you prepare infrastructure to support your application link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/builds_using_buildconfig/#build-strategies[build strategy], you might need to make provisions for link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/scalability_and_performance/#cnf-low-latency-tuning[low-latency] workloads or to link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/nodes/#nodes-pods-secrets[protect sensitive workloads]. You can also configure link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/monitoring/#enabling-monitoring-for-user-defined-projects[monitoring] for application workloads.
If you plan to run link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/windows_container_support_for_openshift/#enabling-windows-container-workloads[Windows workloads], you must enable link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/networking/#configuring-hybrid-networking[hybrid networking with OVN-Kubernetes] during the installation process; hybrid networking cannot be enabled after your cluster is installed.

[id="supported-installation-methods-for-different-platforms"]
== Supported installation methods for different platforms

You can perform different types of installations on different platforms.

[NOTE]
====
Not all installation options are supported for all platforms, as shown in the following tables. A checkmark indicates that the option is supported and links to the relevant section.
====

.Installer-provisioned infrastructure options
//This table is for all flavors of OpenShift, except OKD. A separate table is required because OKD does not support multiple AWS architecture types. Trying to maintain one table using conditions, while convenient, is very fragile and prone to publishing errors.
ifndef::openshift-origin[]
|===
||Alibaba |AWS (64-bit x86) |AWS (64-bit ARM) |Azure (64-bit x86) |Azure (64-bit ARM)|Azure Stack Hub |GCP (64-bit x86) |GCP (64-bit ARM) |Nutanix |{rh-openstack} |Bare metal (64-bit x86) |Bare metal (64-bit ARM) |vSphere |{ibm-cloud-name} |{ibm-z-name} |{ibm-power-name} |{ibm-power-server-name}

|Default
|xref:installing-alibaba-default[&#10003;]
|xref:installing-aws-default[&#10003;]
|xref:installing-aws-default[&#10003;]
|xref:installing-azure-default[&#10003;]
|xref:installing-azure-default[&#10003;]
|xref:installing-azure-stack-hub-default[&#10003;]
|xref:installing-gcp-default[&#10003;]
|xref:installing-gcp-default[&#10003;]
|xref:installing-nutanix-installer-provisioned[&#10003;]
|
|xref:ipi-install-overview[&#10003;]
|xref:ipi-install-overview[&#10003;]
|xref:installing-vsphere-installer-provisioned[&#10003;]
|xref:installing-ibm-cloud-customizations[&#10003;]
|
|
|

|Custom
|xref:installing-alibaba-customizations[&#10003;]
|xref:installing-aws-customizations[&#10003;]
|xref:installing-aws-customizations[&#10003;]
|xref:installing-azure-customizations[&#10003;]
|xref:installing-azure-customizations[&#10003;]
|xref:installing-azure-stack-hub-default[&#10003;]
|xref:installing-gcp-customizations[&#10003;]
|xref:installing-gcp-customizations[&#10003;]
|xref:installing-nutanix-installer-provisioned[&#10003;]
|xref:installing-openstack-installer-custom[&#10003;]
|
|
|xref:installing-vsphere-installer-provisioned-customizations[&#10003;]
|xref:installing-ibm-cloud-customizations[&#10003;]
|
|
|xref:installing-ibm-power-vs-customizations[&#10003;]


|Network customization
|xref:installing-alibaba-network-customizations[&#10003;]
|xref:installing-aws-network-customizations[&#10003;]
|xref:installing-aws-network-customizations[&#10003;]
|xref:installing-azure-network-customizations[&#10003;]
|xref:installing-azure-network-customizations[&#10003;]
|xref:installing-azure-stack-hub-network-customizations[&#10003;]
|xref:installing-gcp-network-customizations[&#10003;]
|xref:installing-gcp-network-customizations[&#10003;]
|
|
|
|
|xref:installing-vsphere-installer-provisioned-network-customizations[&#10003;]
|xref:installing-ibm-cloud-network-customizations[&#10003;]
|
|
|

|Restricted network
|
|xref:installing-restricted-networks-aws-installer-provisioned[&#10003;]
|xref:installing-restricted-networks-aws-installer-provisioned[&#10003;]
|xref:installing-restricted-networks-azure-installer-provisioned[&#10003;]
|xref:installing-restricted-networks-azure-installer-provisioned[&#10003;]
|
|xref:installing-restricted-networks-gcp-installer-provisioned[&#10003;]
|xref:installing-restricted-networks-gcp-installer-provisioned[&#10003;]
|xref:installing-restricted-networks-nutanix-installer-provisioned[&#10003;]
|xref:installing-openstack-installer-restricted[&#10003;]
|xref:ipi-install-installation-workflow[&#10003;]
|xref:ipi-install-installation-workflow[&#10003;]
|xref:installing-restricted-networks-installer-provisioned-vsphere[&#10003;]
|xref:installing-ibm-cloud-restricted[&#10003;]
|
|
|xref:installing-restricted-networks-ibm-power-vs[&#10003;]

|Private clusters
|
|xref:installing-aws-private[&#10003;]
|xref:installing-aws-private[&#10003;]
|xref:installing-azure-private[&#10003;]
|xref:installing-azure-private[&#10003;]
|
|xref:installing-gcp-private[&#10003;]
|xref:installing-gcp-private[&#10003;]
|
|
|
|
|
|xref:installing-ibm-cloud-private[&#10003;]
|
|
|xref:installing-ibm-power-vs-private-cluster[&#10003;]

|Existing virtual private networks
|
|xref:installing-aws-vpc[&#10003;]
|xref:installing-aws-vpc[&#10003;]
|xref:installing-azure-vnet[&#10003;]
|xref:installing-azure-vnet[&#10003;]
|
|xref:installing-gcp-vpc[&#10003;]
|xref:installing-gcp-vpc[&#10003;]
|
|
|
|
|
|xref:installing-ibm-cloud-vpc[&#10003;]
|
|
|xref:installing-ibm-powervs-vpc[&#10003;]

|Government regions
|
|xref:installing-aws-government-region[&#10003;]
|
|xref:installing-azure-government-region[&#10003;]
|
|
|
|
|
|
|
|
|
|
|
|
|

|Secret regions
|
|xref:installing-aws-secret-region[&#10003;]
|
|
|
|
|
|
|
|
|
|
|
|
|
|
|

|China regions
|
|xref:installing-aws-china-region[&#10003;]
|
|
|
|
|
|
|
|
|
|
|
|
|
|
|
|===
endif::openshift-origin[]

//This table is for OKD only. A separate table is required because OKD does not support multiple AWS architecture types. Trying to maintain one table using conditions, while convenient, is very fragile and prone to publishing errors.
ifdef::openshift-origin[]
|===
||Alibaba |AWS |Azure |Azure Stack Hub |GCP |Nutanix |{rh-openstack} |Bare metal |vSphere |{ibm-cloud-name} |{ibm-z-name} |{ibm-power-name}


|Default
|xref:installing-alibaba-default[&#10003;]
|xref:installing-aws-default[&#10003;]
|xref:installing-azure-default[&#10003;]
|xref:installing-azure-default[&#10003;]
|xref:installing-gcp-default[&#10003;]
|xref:installing-nutanix-installer-provisioned[&#10003;]
|
|xref:ipi-install-overview[&#10003;]
|xref:installing-vsphere-installer-provisioned[&#10003;]
|xref:installing-ibm-cloud-customizations[&#10003;]
|
|

|Custom
|xref:installing-alibaba-customizations[&#10003;]
|xref:installing-aws-customizations[&#10003;]
|xref:installing-azure-customizations[&#10003;]
|xref:installing-azure-default[&#10003;]
|xref:installing-gcp-customizations[&#10003;]
|xref:installing-nutanix-installer-provisioned[&#10003;]
|xref:installing-openstack-installer-custom[&#10003;]
|
|xref:installing-vsphere-installer-provisioned-customizations[&#10003;]
|xref:installing-ibm-cloud-customizations[&#10003;]
|
|

|Network customization
|xref:installing-alibaba-network-customizations[&#10003;]
|xref:installing-aws-network-customizations[&#10003;]
|xref:installing-azure-network-customizations[&#10003;]
|xref:installing-azure-stack-hub-network-customizations[&#10003;]
|xref:installing-gcp-network-customizations[&#10003;]
|
|
|
|xref:installing-vsphere-installer-provisioned-network-customizations[&#10003;]
|xref:installing-ibm-cloud-network-customizations[&#10003;]
|
|

|Restricted network
|
|xref:installing-restricted-networks-aws-installer-provisioned[&#10003;]
|
|
|xref:installing-restricted-networks-gcp-installer-provisioned[&#10003;]
|xref:installing-restricted-networks-nutanix-installer-provisioned[&#10003;]
|xref:installing-openstack-installer-restricted[&#10003;]
|
|xref:installing-restricted-networks-installer-provisioned-vsphere[&#10003;]
|xref:installing-ibm-cloud-restricted[&#10003;]
|
|

|Private clusters
|
|xref:installing-aws-private[&#10003;]
|xref:installing-azure-private[&#10003;]
|
|xref:installing-gcp-private[&#10003;]
|
|
|
|
|xref:installing-ibm-cloud-private[&#10003;]
|
|

|Existing virtual private networks
|
|xref:installing-aws-vpc[&#10003;]
|xref:installing-azure-vnet[&#10003;]
|
|xref:installing-gcp-vpc[&#10003;]
|
|
|
|
|xref:installing-ibm-cloud-vpc[&#10003;]
|
|

|Government regions
|
|xref:installing-aws-government-region[&#10003;]
|xref:installing-azure-government-region[&#10003;]
|
|
|
|
|
|
|
|
|

|Secret regions
|
|xref:installing-aws-secret-region[&#10003;]
|
|
|
|
|
|
|
|
|
|

|China regions
|
|xref:installing-aws-china-region[&#10003;]
|
|
|
|
|
|
|
|
|
|
|===
endif::openshift-origin[]

.User-provisioned infrastructure options
//This table is for all flavors of OpenShift, except OKD. A separate table is required because OKD does not support multiple AWS architecture types. Trying to maintain one table using conditions, while convenient, is very fragile and prone to publishing errors.
ifndef::openshift-origin[]
|===
||Alibaba |AWS (64-bit x86) |AWS (64-bit ARM) |Azure (64-bit x86) |Azure (64-bit ARM) |Azure Stack Hub |GCP (64-bit x86) |GCP (64-bit ARM) |Nutanix |{rh-openstack} |Bare metal (64-bit x86) |Bare metal (64-bit ARM) |vSphere |{ibm-cloud-name} |{ibm-z-name} |{ibm-z-name} with {op-system-base} KVM |{ibm-power-name} |Platform agnostic


|Custom
|
|xref:installing-aws-user-infra[&#10003;]
|xref:installing-aws-user-infra[&#10003;]
|xref:installing-azure-user-infra[&#10003;]
|xref:installing-azure-user-infra[&#10003;]
|xref:installing-azure-stack-hub-user-infra[&#10003;]
|xref:installing-gcp-user-infra[&#10003;]
|xref:installing-gcp-user-infra[&#10003;]
|
|xref:installing-openstack-user[&#10003;]
|xref:installing-bare-metal[&#10003;]
|xref:installing-bare-metal[&#10003;]
|xref:installing-vsphere[&#10003;]
|
|xref:installing-ibm-z[&#10003;]
|xref:installing-ibm-z-kvm[&#10003;]
|xref:installing-ibm-power[&#10003;]
|xref:installing-platform-agnostic[&#10003;]


|Network customization
|
|
|
|
|
|
|
|
|
|
|xref:installing-bare-metal-network-customizations[&#10003;]
|xref:installing-bare-metal-network-customizations[&#10003;]
|xref:installing-vsphere-network-customizations[&#10003;]
|
|
|
|
|

|Restricted network
|
|xref:installing-restricted-networks-aws[&#10003;]
|xref:installing-restricted-networks-aws[&#10003;]
|
|
|
|xref:installing-restricted-networks-gcp[&#10003;]
|xref:installing-restricted-networks-gcp[&#10003;]
|
|
|xref:installing-restricted-networks-bare-metal[&#10003;]
|xref:installing-restricted-networks-bare-metal[&#10003;]
|xref:installing-restricted-networks-vsphere[&#10003;]
|
|xref:installing-restricted-networks-ibm-z[&#10003;]
|xref:installing-restricted-networks-ibm-z-kvm[&#10003;]
|xref:installing-restricted-networks-ibm-power[&#10003;]
|

|Shared VPC hosted outside of cluster project
|
|
|
|
|
|
|xref:installing-gcp-user-infra-vpc[&#10003;]
|xref:installing-gcp-user-infra-vpc[&#10003;]
|
|
|
|
|
|
|
|
|
|
|
|===
endif::openshift-origin[]

//This table is for OKD only. A separate table is required because OKD does not support multiple AWS architecture types. Trying to maintain one table using conditions, while convenient, is very fragile and prone to publishing errors.
ifdef::openshift-origin[]
|===
||Alibaba |AWS |Azure |Azure Stack Hub |GCP |Nutanix |{rh-openstack}|Bare metal |vSphere |{ibm-cloud-name} |{ibm-z-name} |{ibm-z-name} with {op-system-base} KVM |{ibm-power-name} |Platform agnostic


|Custom
|
|xref:installing-aws-user-infra[&#10003;]
|xref:installing-azure-user-infra[&#10003;]
|xref:installing-azure-stack-hub-user-infra[&#10003;]
|xref:installing-gcp-user-infra[&#10003;]
|
|xref:installing-openstack-user[&#10003;]
|xref:installing-bare-metal[&#10003;]
|xref:installing-vsphere[&#10003;]
|
|xref:installing-ibm-z[&#10003;]
|xref:installing-ibm-z-kvm[&#10003;]
|xref:installing-ibm-power[&#10003;]
|xref:installing-platform-agnostic[&#10003;]


|Network customization
|
|
|
|
|
|
|
|xref:installing-bare-metal-network-customizations[&#10003;]
|xref:installing-vsphere-network-customizations[&#10003;]
|
|
|
|
|

|Restricted network
|
|xref:installing-restricted-networks-aws[&#10003;]
|
|
|xref:installing-restricted-networks-gcp[&#10003;]
|
|
|xref:installing-restricted-networks-bare-metal[&#10003;]
|xref:installing-restricted-networks-vsphere[&#10003;]
|
|xref:installing-restricted-networks-ibm-z[&#10003;]
|xref:installing-restricted-networks-ibm-z-kvm[&#10003;]
|xref:installing-restricted-networks-ibm-power[&#10003;]
|

|Shared VPC hosted outside of cluster project
|
|
|
|
|xref:installing-gcp-user-infra-vpc[&#10003;]
|
|
|
|
|
|
|
|
|
|===
endif::openshift-origin[]

////
.Special use cases
|===
|Single Node

|xref:../installing/installing_sno/install-sno-installing-sno.adoc#installing-sno[&#10003;]


|===
////
// sync
