:_mod-docs-content-type: ASSEMBLY
[id="installing-mirroring-disconnected"]
= Mirroring images for a disconnected installation using the oc-mirror plugin
include::../includes/common-attributes.adoc[]
:context: installing-mirroring-disconnected


Running your cluster in a restricted network without direct internet connectivity is possible by installing the cluster from a mirrored set of {product-title} container images in a private registry. This registry must be running at all times as long as the cluster is running. See the xref:prerequisites_installing-mirroring-disconnected[Prerequisites] section for more information.

You can use the oc-mirror OpenShift CLI (`oc`) plugin to mirror images to a mirror registry in your fully or partially disconnected environments. You must run oc-mirror from a system with internet connectivity in order to download the required images from the official Red Hat registries.

The following steps outline the high-level workflow on how to use the oc-mirror plugin to mirror images to a mirror registry:

. Create an image set configuration file.
. Mirror the image set to the mirror registry by using one of the following methods:
** Mirror an image set directly to the mirror registry.
** Mirror an image set to disk, transfer the image set to the target environment, then upload the image set to the target mirror registry.
. Configure your cluster to use the resources generated by the oc-mirror plugin.
. Repeat these steps to update your mirror registry as necessary.

// About the oc-mirror plugin
include::../includes/oc-mirror-about.adoc[leveloffset=+1]

// oc-mirror compatibility and support
include::../includes/oc-mirror-support.adoc[leveloffset=+1]

// About the mirror registry
include::../includes/installation-about-mirror-registry.adoc[leveloffset=+1]

[role="_additional-resources"]
.Additional resources

* For information about viewing the CRI-O logs to view the image source, see xref:viewing-the-image-pull-source_validating-an-installation[Viewing the image pull source].

[id="prerequisites_installing-mirroring-disconnected"]
== Prerequisites

* You must have a container image registry that supports link:https://docs.docker.com/registry/spec/manifest-v2-2[Docker v2-2] in the location that will host the {product-title} cluster, such as Red Hat Quay.
+
[NOTE]
====
If you use Red Hat Quay, you must use version 3.6 or later with the oc-mirror plugin. If you have an entitlement to Red Hat Quay, see the documentation on deploying Red Hat Quay link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html/deploy_red_hat_quay_for_proof-of-concept_non-production_purposes/[for proof-of-concept purposes] or link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html/deploying_the_red_hat_quay_operator_on_openshift_container_platform/index[by using the Red Hat Quay Operator]. If you need additional assistance selecting and installing a registry, contact your sales representative or Red Hat Support.
====
+
If you do not already have an existing solution for a container image registry, subscribers of {product-title} are provided a xref:installing-mirroring-creating-registry[mirror registry for Red Hat OpenShift]. The _mirror registry for Red Hat OpenShift_ is included with your subscription and is a small-scale container registry that can be used to mirror the required container images of {product-title} in disconnected installations.

[id="mirroring-preparing-your-hosts"]
== Preparing your mirror hosts

Before you can use the oc-mirror plugin to mirror images, you must install the plugin and create a container image registry credentials file to allow the mirroring from Red Hat to your mirror.

// Installing the oc-mirror OpenShift CLI plugin
include::../includes/oc-mirror-installing-plugin.adoc[leveloffset=+2]

[role="_additional-resources"]
.Additional resources

* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/cli_tools/#cli-installing-plugins_cli-extend-plugins[Installing and using CLI plugins]

// Configuring credentials that allow images to be mirrored
include::../includes/installation-adding-registry-pull-secret.adoc[leveloffset=+2]

// Creating the image set configuration
include::../includes/oc-mirror-creating-image-set-config.adoc[leveloffset=+1]

[role="_additional-resources"]
.Additional resources

* xref:oc-mirror-imageset-config-params_installing-mirroring-disconnected[Image set configuration parameters]
* xref:oc-mirror-image-set-examples_installing-mirroring-disconnected[Image set configuration examples]
* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/updating_clusters/#update-service-overview_updating-restricted-network-cluster-osus[Using the OpenShift Update Service in a disconnected environment]

[id="mirroring-image-set"]
== Mirroring an image set to a mirror registry

You can use the oc-mirror CLI plugin to mirror images to a mirror registry in a xref:mirroring-image-set-partial[partially disconnected environment] or in a xref:mirroring-image-set-full[fully disconnected environment].

These procedures assume that you already have your mirror registry set up.

[id="mirroring-image-set-partial"]
=== Mirroring an image set in a partially disconnected environment

In a partially disconnected environment, you can mirror an image set directly to the target mirror registry.

// Mirroring from mirror to mirror
include::../includes/oc-mirror-mirror-to-mirror.adoc[leveloffset=+3]

[id="mirroring-image-set-full"]
=== Mirroring an image set in a fully disconnected environment

To mirror an image set in a fully disconnected environment, you must first xref:oc-mirror-mirror-to-disk_installing-mirroring-disconnected[mirror the image set to disk], then xref:oc-mirror-disk-to-mirror_installing-mirroring-disconnected[mirror the image set file on disk to a mirror].

// Mirroring from mirror to disk
include::../includes/oc-mirror-mirror-to-disk.adoc[leveloffset=+3]

// Mirroring from disk to mirror in a disconnected environment
include::../includes/oc-mirror-disk-to-mirror.adoc[leveloffset=+3]

// Configuring your cluster to use the resources generated by oc-mirror
include::../includes/oc-mirror-updating-cluster-manifests.adoc[leveloffset=+1]

[id="updating-mirror-registry-content"]
== Keeping your mirror registry content updated

After your target mirror registry is populated with the initial image set, be sure to update it regularly so that it has the latest content. You can optionally set up a cron job, if possible, so that the mirror registry is updated on a regular basis.

Ensure that you update your image set configuration to add or remove {product-title} and Operator releases as necessary. Any images that are removed are pruned from the mirror registry.

// About updating your mirror registry content
include::../includes/oc-mirror-updating-registry-about.adoc[leveloffset=+2]

// Updating your mirror registry content
include::../includes/oc-mirror-differential-updates.adoc[leveloffset=+2]

[role="_additional-resources"]
.Additional resources

* xref:oc-mirror-image-set-examples_installing-mirroring-disconnected[Image set configuration examples]
* xref:mirroring-image-set-partial[Mirroring an image set in a partially disconnected environment]
* xref:mirroring-image-set-full[Mirroring an image set in a fully disconnected environment]
* xref:oc-mirror-updating-cluster-manifests_installing-mirroring-disconnected[Configuring your cluster to use the resources generated by oc-mirror]

// Performing a dry run
include::../includes/oc-mirror-dry-run.adoc[leveloffset=+1]

// Including local OCI Operator catalogs
include::../includes/oc-mirror-oci-format.adoc[leveloffset=+1]

[role="_additional-resources"]
.Additional resources

// TODO: This title might need to update per sebastian's PR
* xref:oc-mirror-updating-cluster-manifests_installing-mirroring-disconnected[Configuring your cluster to use the resources generated by oc-mirror]

// Image set configuration parameters
include::../includes/oc-mirror-imageset-config-params.adoc[leveloffset=+1]

// Image set configuration examples
include::../includes/oc-mirror-image-set-config-examples.adoc[leveloffset=+1]

// Command reference for oc-mirror
include::../includes/oc-mirror-command-reference.adoc[leveloffset=+1]

[role="_additional-resources"]
[id="additional-resources_installing-mirroring-disconnected"]
== Additional resources

* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/updating_clusters/#about-restricted-network-updates[About cluster updates in a disconnected environment]
