:_mod-docs-content-type: ASSEMBLY
[id="albo-sts-cluster"]
= Installing AWS Load Balancer Operator on a Security Token Service cluster
include::../includes/common-attributes.adoc[]
:context: albo-sts-cluster


You can install the AWS Load Balancer (ALB) Operator on a Security Token Service (STS) cluster.

The ALB Operator relies on a `CredentialsRequest` to bootstrap the Operator and for the `AWSLoadBalancerController` instance. The ALB Operator waits until the required secrets are created and available.

[id="creating-iam-role-albo-operator_{context}"]
== Creating an IAM role for the AWS Load Balancer Operator

An additional IAM role is required to successfully install the ALB Operator on a Security Token Service (STS) cluster. The IAM role is required to interact with subnets and Virtual Private Clouds (VPCs). The Operator generates a `CredentialsRequest` with this role to bootstrap itself.

There are two options for creating the IAM role:

* Using `ccoctl` and a predefined `CredentialsRequest`.
* Using the AWS CLI and predefined AWS manifests.

Use the AWS CLI if your environment does not support the `ccoctl` command.

include::../includes/using-ccoctl-create-iam-role-alb-operator.adoc[leveloffset=+2]
include::../includes/using-aws-cli-create-iam-role-alb-operator.adoc[leveloffset=+2]

include::../includes/specifying-role-arn-albo-sts.adoc[leveloffset=+1]

[id="creating-iam-role-albo-controller_{context}"]
== Creating an IAM role for the AWS Load Balancer Controller

The `CredentialsRequest` for the AWS Load Balancer Controller must be set with a manually provisioned IAM role.

There are two options for creating the IAM role:

* Using `ccoctl` and a predefined `CredentialsRequest`.
* Using the AWS CLI and predefined AWS manifests.

Use the AWS CLI if your environment does not support the `ccoctl` command.

include::../includes/using-ccoctl-create-iam-role-alb-controller.adoc[leveloffset=+2]
include::../includes/using-aws-cli-create-iam-role-alb-controller.adoc[leveloffset=+2]

[role="_additional-resources"]
== Additional resources
* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/installing/#cco-ccoctl-configuring_installing-aws-customizations[Configuring the Cloud Credential Operator utility]
