:_mod-docs-content-type: ASSEMBLY
include::../includes/common-attributes.adoc[]
[id="about-virt"]
= About {VirtProductName}
:context: about-virt


Learn about {VirtProductName}'s capabilities and support scope.

include::../includes/virt-what-you-can-do-with-virt.adoc[leveloffset=+1]

// This line is attached to the above `virt-what-you-can-do-with-virt` module.
// It is included here in the assembly because of the xref ban.

You can use {VirtProductName} with link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/networking/#about-ovn-kubernetes[OVN-Kubernetes], link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/networking/#about-openshift-sdn[OpenShift SDN], or one of the other certified network plugins listed in link:https://access.redhat.com/articles/5436171[Certified OpenShift CNI Plug-ins].

You can check your {VirtProductName} cluster for compliance issues by installing the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/security_and_compliance/#understanding-compliance[Compliance Operator] and running a scan with the `ocp4-moderate` and `ocp4-moderate-node` link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/security_and_compliance/#compliance-operator-supported-profiles[profiles]. The Compliance Operator uses OpenSCAP, a link:https://www.nist.gov/[NIST-certified tool], to scan and enforce security policies.

include::../includes/virt-supported-cluster-version.adoc[leveloffset=+2]

include::../includes/virt-about-storage-volumes-for-vm-disks.adoc[leveloffset=+1]

include::../includes/virt-sno-differences.adoc[leveloffset=+1]

[role="_additional-resources"]
[id="additional-resources_about-virt"]
== Additional resources

* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/storage/#openshift-storage-common-terms_storage-overview[Glossary of common terms for {product-title} storage]
* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/installing/#install-sno-about-installing-on-a-single-node_install-sno-preparing[About {sno}]
* link:https://cloud.redhat.com/blog/using-the-openshift-assisted-installer-service-to-deploy-an-openshift-cluster-on-metal-and-vsphere[Assisted installer]
* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/nodes/#priority-preemption-other_nodes-pods-priority[Pod disruption budgets]
* xref:virt-about-live-migration[About live migration]
* xref:eviction-strategies[Eviction strategies]
* link:https://access.redhat.com/articles/6994974[Tuning & Scaling Guide]