:_mod-docs-content-type: ASSEMBLY
[id="logging-network-policy"]
= Logging for egress firewall and network policy rules
include::../includes/common-attributes.adoc[]
:context: logging-network-policy


As a cluster administrator, you can configure audit logging for your cluster and enable logging for one or more namespaces. {product-title} produces audit logs for both egress firewalls and network policies.

[NOTE]
====
Audit logging is available for only the xref:about-ovn-kubernetes[OVN-Kubernetes network plugin].
====

include::../includes/nw-networkpolicy-audit-concept.adoc[leveloffset=+1]

[id="network-policy-audit-configuration-{context}"]
== Audit configuration

The configuration for audit logging is specified as part of the OVN-Kubernetes cluster network provider configuration. The following YAML illustrates the default values for the audit logging:

.Audit logging configuration
[source,yaml]
----
apiVersion: operator.openshift.io/v1
kind: Network
metadata:
  name: cluster
spec:
  defaultNetwork:
    ovnKubernetesConfig:
      policyAuditConfig:
        destination: "null"
        maxFileSize: 50
        rateLimit: 20
        syslogFacility: local0
----

The following table describes the configuration fields for audit logging.

include::../includes/nw-operator-cr.adoc[tag=policy-audit]

include::../includes/nw-networkpolicy-audit-configure.adoc[leveloffset=+1]
include::../includes/nw-networkpolicy-audit-enable.adoc[leveloffset=+1]
include::../includes/nw-networkpolicy-audit-disable.adoc[leveloffset=+1]

[id="{context}-additional-resources"]
[role="_additional-resources"]
== Additional resources

* xref:about-network-policy[About network policy]
* xref:configuring-egress-firewall-ovn[Configuring an egress firewall for a project]
