[id="persistent-storage-csi-ibm-vpc-block"]
= {ibm-title} VPC Block CSI Driver Operator
include::../includes/common-attributes.adoc[]
:context: persistent-storage-csi-ibm-vpc-block


== Overview

{product-title} is capable of provisioning persistent volumes (PVs) using the Container Storage Interface (CSI) driver for {ibm-name} Virtual Private Cloud (VPC) Block Storage.

Familiarity with xref:understanding-persistent-storage[persistent storage] and xref:persistent-storage-csi[configuring CSI volumes] is recommended when working with a CSI Operator and driver.

To create CSI-provisioned PVs that mount to {ibm-name} VPC Block storage assets, {product-title} installs the {ibm-name} VPC Block CSI Driver Operator and the {ibm-name} VPC Block CSI driver by default in the `openshift-cluster-csi-drivers` namespace.

* The _{ibm-name} VPC Block CSI Driver Operator_ provides three storage classes named `ibmc-vpc-block-10iops-tier` (default), `ibmc-vpc-block-5iops-tier`, and `ibmc-vpc-block-custom` for different tiers that you can use to create persistent volume claims (PVCs). The {ibm-name} VPC Block CSI Driver Operator supports dynamic volume provisioning by allowing storage volumes to be created on demand, eliminating the need for cluster administrators to pre-provision storage. You can disable this default storage class if desired (see xref:persistent-storage-csi-sc-manage[Managing the default storage class]).

* The _{ibm-name} VPC Block CSI driver_ enables you to create and mount {ibm-name} VPC Block PVs.

include::../includes/persistent-storage-csi-about.adoc[leveloffset=+1]

ifndef::openshift-rosa,openshift-dedicated[]
include::../includes/persistent-storage-byok.adoc[leveloffset=+1]

For information about installing with user-managed encryption for IBM VPC, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/installing/#user-managed-encryption[User-managed encryption for IBM Cloud] and link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/installing/#preparing-to-install-on-ibm-cloud-1[Preparing to install on IBM Cloud].
endif::openshift-rosa,openshift-dedicated[]

[role="_additional-resources"]
.Additional resources
* xref:persistent-storage-csi[Configuring CSI volumes]
