:_mod-docs-content-type: ASSEMBLY
[id="persistent-storage-csi-gcp-pd"]
= GCP PD CSI Driver Operator
include::../includes/common-attributes.adoc[]
:context: persistent-storage-csi-gcp-pd


== Overview

{product-title} can provision persistent volumes (PVs) using the Container Storage Interface (CSI) driver for Google Cloud Platform (GCP) persistent disk (PD) storage.

:FeatureName: GCP PD CSI Driver Operator

Familiarity with xref:understanding-persistent-storage[persistent storage] and xref:persistent-storage-csi[configuring CSI volumes] is recommended when working with a Container Storage Interface (CSI) Operator and driver.

To create CSI-provisioned persistent volumes (PVs) that mount to GCP PD storage assets, {product-title} installs the GCP PD CSI Driver Operator and the GCP PD CSI driver by default in the `openshift-cluster-csi-drivers` namespace.

* *GCP PD CSI Driver Operator*: By default, the Operator provides a storage class that you can use to create PVCs. You can disable this default storage class if desired (see xref:persistent-storage-csi-sc-manage[Managing the default storage class]). You also have the option to create the GCP PD storage class as described in xref:persistent-storage-using-gce[Persistent storage using GCE Persistent Disk].

* *GCP PD driver*: The driver enables you to create and mount GCP PD PVs.

[IMPORTANT]
====
{product-title} defaults to using the CSI plugin to provision GCP PD storage.
====

include::../includes/persistent-storage-csi-about.adoc[leveloffset=+1]

include::../includes/persistent-storage-csi-gcp-pd-storage-class-ref.adoc[leveloffset=+1]

include::../includes/persistent-storage-csi-gcp-pd-encrypted-pv.adoc[leveloffset=+1]

ifndef::openshift-rosa,openshift-dedicated[]
include::../includes/persistent-storage-byok.adoc[leveloffset=+1]

For information about installing with user-managed encryption for GCP PD, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/installing/#installation-configuration-parameters_installing-gcp-customizations[Installation configuration parameters].
endif::openshift-rosa,openshift-dedicated[]

[role="_additional-resources"]
== Additional resources
* xref:persistent-storage-using-gce[Persistent storage using GCE Persistent Disk]
* xref:persistent-storage-csi[Configuring CSI volumes]
