:_mod-docs-content-type: ASSEMBLY
[id="persistent-storage-csi-cinder"]
= OpenStack Cinder CSI Driver Operator
include::../includes/common-attributes.adoc[]
:context: persistent-storage-csi-cinder


== Overview

{product-title} is capable of provisioning persistent volumes (PVs) using the Container Storage Interface (CSI) driver for OpenStack Cinder.

Familiarity with xref:understanding-persistent-storage[persistent storage] and xref:persistent-storage-csi[configuring CSI volumes] is recommended when working with a Container Storage Interface (CSI) Operator and driver.

To create CSI-provisioned PVs that mount to OpenStack Cinder storage assets, {product-title} installs the OpenStack Cinder CSI Driver Operator and the OpenStack Cinder CSI driver in the `openshift-cluster-csi-drivers` namespace.

* The _OpenStack Cinder CSI Driver Operator_ provides a CSI storage class that you can use to create PVCs. You can disable this default storage class if desired (see xref:persistent-storage-csi-sc-manage[Managing the default storage class]).

* The _OpenStack Cinder CSI driver_ enables you to create and mount OpenStack Cinder PVs.

For {product-title}, automatic migration from OpenStack Cinder in-tree to the CSI driver is available as a Technology Preview (TP) feature.
With migration enabled, volumes provisioned using the existing in-tree plugin are automatically migrated to use the OpenStack Cinder CSI driver. For more information, see xref:persistent-storage-csi-migration[CSI automatic migration feature].

include::../includes/persistent-storage-csi-about.adoc[leveloffset=+1]

[IMPORTANT]
====
{product-title} defaults to using the CSI plugin to provision Cinder storage.
====

include::../includes/persistent-storage-csi-cinder-storage-class.adoc[leveloffset=+1]

[role="_additional-resources"]
.Additional resources
* xref:persistent-storage-csi[Configuring CSI volumes]
