:_mod-docs-content-type: ASSEMBLY
[id="configuring-ingress-cluster-traffic-ingress-controller"]
= Configuring ingress cluster traffic using an Ingress Controller
include::../includes/common-attributes.adoc[]
:context: configuring-ingress-cluster-traffic-ingress-controller



{product-title} provides methods for communicating from outside the cluster with
services running in the cluster. This method uses an Ingress Controller.

ifdef::openshift-enterprise,openshift-webscale,openshift-origin[]
include::../includes/nw-using-ingress-and-routes.adoc[leveloffset=+1]

[NOTE]
====
The procedures in this section require prerequisites performed by the cluster
administrator.
====

== Prerequisites

Before starting the following procedures, the administrator must:

* Set up the external port to the cluster networking environment so that requests
can reach the cluster.

* Make sure there is at least one user with cluster admin role. To add this role
to a user, run the following command:
+
----
$ oc adm policy add-cluster-role-to-user cluster-admin username
----

* Have an {product-title} cluster with at least one master and at least one node
and a system outside the cluster that has network access to the cluster. This
procedure assumes that the external system is on the same subnet as the cluster.
The additional networking required for external systems on a different subnet is
out-of-scope for this topic.
endif::[]

include::../includes/nw-creating-project-and-service.adoc[leveloffset=+1]

include::../includes/nw-exposing-service.adoc[leveloffset=+1]

// Router sharding
ifdef::openshift-enterprise,openshift-webscale,openshift-origin[]
include::../includes/nw-ingress-sharding-route-labels.adoc[leveloffset=+1]

include::../includes/nw-ingress-sharding-namespace-labels.adoc[leveloffset=+1]

include::../includes/nw-ingress-sharding-route-configuration.adoc[leveloffset=+1]

[role="_additional-resources"]
== Additional resources

The Ingress Operator manages wildcard DNS. For more information, see the following:

* xref:configuring-ingress[Ingress Operator in {product-title}].

* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/installing/#installing-bare-metal[Installing a cluster on bare metal].

* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/installing/#installing-vsphere[Installing a cluster on vSphere].

* xref:about-network-policy[About network policy].

endif::[]
