:_mod-docs-content-type: ASSEMBLY
[id="updating-cluster-web-console"]
= Updating a cluster using the web console
include::../includes/common-attributes.adoc[]
:context: updating-cluster-web-console


////
WARNING: This assembly has been moved into a subdirectory for 4.14+. Changes to this assembly for earlier versions should be done in separate PRs based off of their respective version branches. Otherwise, your cherry picks may fail.

To do: Remove this comment once 4.13 docs are EOL.
////

You can update, or upgrade, an {product-title} cluster by using the web console. The following steps update a cluster within a minor version. You can use the same instructions for updating a cluster between minor versions.

[NOTE]
====
Use the web console or `oc adm upgrade channel _<channel>_` to change the update channel. You can follow the steps in xref:updating-cluster-cli[Updating a cluster using the CLI] to complete the update after you change to a {product-version} channel.
====

include::../includes/before-updating-ocp.adoc[leveloffset=+1]

[IMPORTANT]
====
* When an update is failing to complete, the Cluster Version Operator (CVO) reports the status of any blocking components while attempting to reconcile the update. Rolling your cluster back to a previous version is not supported. If your update is failing to complete, contact Red{nbsp}Hat support.
* Using the `unsupportedConfigOverrides` section to modify the configuration of an Operator is unsupported and might block cluster updates. You must remove this setting before you can update your cluster.
====

include::../includes/update-changing-update-server-web.adoc[leveloffset=+1]

[role="_additional-resources"]
.Additional resources

* xref:understanding-update-channels-releases[Understanding update channels and releases]

include::../includes/machine-health-checks-pausing-web-console.adoc[leveloffset=+1]

include::../includes/update-upgrading-web.adoc[leveloffset=+1]

[role="_additional-resources"]
.Additional resources

* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/operators/#olm-upgrading-operators[Updating installed Operators]

include::../includes/update-conditional-web-console.adoc[leveloffset=+1]

[role="_additional-resources"]
.Additional resources

* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/operators/#olm-upgrading-operators[Updating installed Operators]

* xref:conditional-updates-overview_understanding-update-channels-releases[Update recommendations and Conditional Updates]

include::../includes/update-using-custom-machine-config-pools-canary.adoc[leveloffset=+1]

If you want to use the canary rollout update process, see xref:update-using-custom-machine-config-pools[Performing a canary rollout update].

include::../includes/updating-sno.adoc[leveloffset=+1]

[role="_additional-resources"]
.Additional resources

* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/architecture/#about-machine-config-operator_control-plane[About the Machine Config Operator].