:_mod-docs-content-type: ASSEMBLY
[id="installing-ossm"]
= Installing the Operators
include::../includes/common-attributes.adoc[]
:context: installing-ossm


To install {SMProductName}, first install the required Operators on {product-title} and then create a `ServiceMeshControlPlane` resource to deploy the control plane.

[NOTE]
====
This basic installation is configured based on the default OpenShift settings and is not designed for production use.  Use this default installation to verify your installation, and then configure your service mesh for your specific environment.
====

.Prerequisites
* Read the xref:preparing-ossm-installation[Preparing to install {SMProductName}] process.
ifdef::openshift-rosa[]
* An account with the `cluster-admin` role.
endif::openshift-rosa[]
ifndef::openshift-rosa[]
* An account with the `cluster-admin` role. If you use {product-dedicated}, you must have an account with the `dedicated-admin` role.
endif::openshift-rosa[]

The following steps show how to install a basic instance of {SMProductName} on {product-title}.

include::../includes/ossm-installation-activities.adoc[leveloffset=+1]

[WARNING]
====
Do not install Community versions of the Operators. Community Operators are not supported.
====

include::../includes/ossm-install-ossm-operator.adoc[leveloffset=+1]

ifndef::openshift-rosa[]

include::../includes/ossm-config-operator-infrastructure-node.adoc[leveloffset=+1]

include::../includes/ossm-confirm-operator-infrastructure-node.adoc[leveloffset=+1]

endif::openshift-rosa[]

== Next steps

* The {SMProductName} Operator does not create the {SMProductShortName} custom resource definitions (CRDs) until you deploy a {SMProductShortName} control plane. You can use the `ServiceMeshControlPlane` resource to install and configure the {SMProductShortName} components. For more information, see xref:ossm-create-smcp[Creating the ServiceMeshControlPlane].
