:_mod-docs-content-type: ASSEMBLY
[id="post-install-configuration-overview"]
= Postinstallation configuration overview
include::includes/common-attributes.adoc[]
:context: post-installation-configuration-overview


After installing {product-title}, a cluster administrator can configure and customize the following components:

* Machine
* Bare metal
* Cluster
* Node
* Network
* Storage
* Users
* Alerts and notifications

[id="post-install-tasks"]
== Configuration tasks to perform after installation

Cluster administrators can perform the following postinstallation configuration tasks:

* xref:post-install-machine-configuration-tasks[Configure operating system features]:
Machine Config Operator (MCO) manages `MachineConfig` objects. By using MCO, you can perform the following tasks on an {product-title} cluster:

** Configure nodes by using `MachineConfig` objects
** Configure MCO-related custom resources

* xref:post-install-bare-metal-configuration[Configure bare metal nodes]: The Bare Metal Operator (BMO) implements a Kubernetes API for managing bare metal hosts. It maintains an inventory of available bare metal hosts as instances of the BareMetalHost Custom Resource Definition (CRD). The Bare Metal Operator can:

** Inspect the host's hardware details and report them on the corresponding BareMetalHost. This includes information about CPUs, RAM, disks, NICs, and more.
** Inspect the host's firmware and configure BIOS settings.
** Provision hosts with a desired image.
** Clean a host's disk contents before or after provisioning.

* xref:post-install-cluster-tasks[Configure cluster features]:
As a cluster administrator, you can modify the configuration resources of the major features of an {product-title} cluster. These features include:

** Image registry
** Networking configuration
** Image build behavior
** Identity provider
** The etcd configuration
** Machine set creation to handle the workloads
** Cloud provider credential management

* xref:configuring-private-cluster[Configure cluster components to be private]:
By default, the installation program provisions {product-title} by using a publicly accessible DNS and endpoints. If you want your cluster to be accessible only from within an internal network, configure the following components to be private:

** DNS
** Ingress Controller
** API server

* xref:post-install-node-tasks[Perform node operations]:
By default, {product-title} uses {op-system-first} compute machines.
As a cluster administrator, you can perform the following operations with the machines in your {product-title} cluster:

** Add and remove compute machines
** Add and remove taints and tolerations to the nodes
** Configure the maximum number of pods per node
** Enable Device Manager

* xref:post-install-network-configuration[Configure network]:
After installing {product-title}, you can configure the following:

** Ingress cluster traffic
** Node port service range
** Network policy
** Enabling the cluster-wide proxy

* xref:post-install-storage-configuration[Configure storage]:
By default, containers operate using ephemeral storage or transient local storage. The ephemeral storage has a lifetime limitation. TO store the data for a long time, you must configure persistent storage.
You can configure storage by using one of the following methods:

** *Dynamic provisioning*: You can dynamically provision storage on demand by defining and creating storage classes that control different levels of storage, including storage access.

** *Static provisioning*: You can use Kubernetes persistent volumes to make existing storage available to a cluster. Static provisioning can support various device configurations and mount options.

* xref:post-install-preparing-for-users[Configure users]:
OAuth access tokens allow users to authenticate themselves to the API. As a cluster administrator, you can configure OAuth to perform the following tasks:
+
* Specify an identity provider
* Use role-based access control to define and supply permissions to users
* Install an Operator from OperatorHub

* xref:configuring-alert-notifications[Manage alerts and notifications]:
By default, firing alerts are displayed on the Alerting UI of the web console. You can also configure {product-title} to send alert notifications to external systems.
