:_mod-docs-content-type: ASSEMBLY
[id="installing-vsphere-post-installation-configuration"]
= Configuring the vSphere connection settings after an installation
include::includes/common-attributes.adoc[]
:context: installing-vsphere-post-installation-configuration


After installing an {product-title} cluster on vSphere with the platform integration feature enabled, you might need to update the vSphere connection settings manually, depending on the installation method.

For installations using the Assisted Installer, you must update the connection settings. This is because the Assisted Installer adds default connection settings to the *vSphere connection configuration* wizard as placeholders during the installation.

For installer-provisioned or user-provisioned infrastructure installations, you should have entered valid connection settings during the installation. You can use the *vSphere connection configuration* wizard at any time to validate or modify the connection settings, but this is not mandatory for completing the installation.


include::includes/configuring-vsphere-connection-settings.adoc[leveloffset=+1]

include::includes/configuring-vsphere-verifying-configuration.adoc[leveloffset=+1]

For instructions on creating storage objects, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/storage/#dynamic-provisioning[Dynamic provisioning].
