:_mod-docs-content-type: ASSEMBLY
:context: post-install-machine-configuration-tasks
[id="post-install-machine-configuration-tasks"]
= Postinstallation machine configuration tasks
include::includes/common-attributes.adoc[]


There are times when you need to make changes to the operating systems running on {product-title} nodes. This can include changing settings for network time service, adding kernel arguments, or configuring journaling in a specific way.

Aside from a few specialized features, most changes to operating systems on {product-title} nodes can be done by creating what are referred to as `MachineConfig` objects that are managed by the Machine Config Operator.

Tasks in this section describe how to use features of the Machine Config Operator to configure operating system features on {product-title} nodes.

[IMPORTANT]
====
NetworkManager stores new network configurations to `/etc/NetworkManager/system-connections/` in a key file format.

Previously, NetworkManager stored new network configurations to `/etc/sysconfig/network-scripts/` in the ifcfg format. Starting with RHEL 9.0, RHEL stores new network configurations at `/etc/NetworkManager/system-connections/` in a key file format. The connections configurations stored to `/etc/sysconfig/network-scripts/` in the old format still work uninterrupted. Modifications in existing profiles continue updating the older files.
====

[id="understanding-the-machine-config-operator"]
== Understanding the Machine Config Operator

include::includes/machine-config-operator.adoc[leveloffset=+2]
include::includes/machine-config-overview.adoc[leveloffset=+2]
include::includes/machine-config-drift-detection.adoc[leveloffset=+2]
include::includes/checking-mco-status.adoc[leveloffset=+2]
include::includes/checking-mco-node-status.adoc[leveloffset=+2]
include::includes/checking-mco-status-certs.adoc[leveloffset=+2]

[id="using-machineconfigs-to-change-machines"]
== Using MachineConfig objects to configure nodes

You can use the tasks in this section to create `MachineConfig` objects that modify files, systemd unit files, and other operating system features running on {product-title} nodes. For more ideas on working with machine configs, see content related to link:https://access.redhat.com/solutions/3868301[updating] SSH authorized keys, link:https://access.redhat.com/verify-images-ocp4[verifying image signatures], link:https://access.redhat.com/solutions/4727321[enabling SCTP], and link:https://access.redhat.com/solutions/5170251[configuring iSCSI initiatornames] for {product-title}.

{product-title} supports link:https://coreos.github.io/ignition/configuration-v3_2/[Ignition specification version 3.2]. All new machine configs you create going forward should be based on Ignition specification version 3.2. If you are upgrading your {product-title} cluster, any existing Ignition specification version 2.x machine configs will be translated automatically to specification version 3.2.

There might be situations where the configuration on a node does not fully match what the currently-applied machine config specifies. This state is called _configuration drift_. The Machine Config Daemon (MCD) regularly checks the nodes for configuration drift. If the MCD detects configuration drift, the MCO marks the node `degraded` until an administrator corrects the node configuration. A degraded node is online and operational, but, it cannot be updated. For more information on configuration drift, see xref:machine-config-drift-detection_post-install-machine-configuration-tasks[Understanding configuration drift detection].

[TIP]
====
Use the following "Configuring chrony time service" procedure as a model for how to go about adding other configuration files to {product-title} nodes.
====

include::includes/installation-special-config-chrony.adoc[leveloffset=+2]

[role="_additional-resources"]
.Additional resources

* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/installing/#installation-special-config-butane_installing-customizing[Creating machine configs with Butane]

include::includes/cnf-disable-chronyd.adoc[leveloffset=+2]
include::includes/nodes-nodes-kernel-arguments.adoc[leveloffset=+2]
include::includes/rhcos-enabling-multipath-day-2.adoc[leveloffset=+2]

[role="_additional-resources"]
.Additional resources

* See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/installing/#rhcos-enabling-multipath_installing-bare-metal[Enabling multipathing with kernel arguments on RHCOS] for more information about enabling multipathing during installation time.

include::includes/nodes-nodes-rtkernel-arguments.adoc[leveloffset=+2]
include::includes/machineconfig-modify-journald.adoc[leveloffset=+2]

[role="_additional-resources"]
.Additional resources

* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/installing/#installation-special-config-butane_installing-customizing[Creating machine configs with Butane]

include::includes/rhcos-add-extensions.adoc[leveloffset=+2]
include::includes/rhcos-load-firmware-blobs.adoc[leveloffset=+2]

[role="_additional-resources"]
.Additional resources

* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/installing/#installation-special-config-butane_installing-customizing[Creating machine configs with Butane]

include::includes/core-user-password.adoc[leveloffset=+2]

[id="configuring-machines-with-custom-resources"]
== Configuring MCO-related custom resources

Besides managing `MachineConfig` objects, the MCO manages two custom resources (CRs): `KubeletConfig` and `ContainerRuntimeConfig`. Those CRs let you change node-level settings impacting how the Kubelet and CRI-O container runtime services behave.

include::includes/create-a-kubeletconfig-crd-to-edit-kubelet-parameters.adoc[leveloffset=+2]
include::includes/create-a-containerruntimeconfig-crd.adoc[leveloffset=+2]
include::includes/set-the-default-max-container-root-partition-size-for-overlay-with-crio.adoc[leveloffset=+2]


