:_mod-docs-content-type: ASSEMBLY
[id="nutanix-failure-domains"]
= Fault tolerant deployments using multiple Prism Elements
include::../includes/common-attributes.adoc[]
:context: nutanix-failure-domains


By default, the installation program installs control plane and compute machines into a single Nutanix Prism Element (cluster). To improve the fault tolerance of your {product-title} cluster, you can specify that these machines be distributed across multiple Nutanix clusters by configuring failure domains.

A failure domain represents an additional Prism Element instance that is available to {product-title} machine pools during and after installation.

include::../includes/installation-nutanix-failure-domains-req.adoc[leveloffset=+1]

== Installation method and failure domain configuration

The {product-title} installation method determines how and when you configure failure domains:

* If you deploy using installer-provisioned infrastructure, you can configure failure domains in the installation configuration file before deploying the cluster. For more information, see xref:installation-configuring-nutanix-failure-domains_installing-nutanix-installer-provisioned[Configuring failure domains].
+
You can also configure failure domains after the cluster is deployed. For more information about configuring failure domains post-installation, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/postinstallation_configuration/#adding-failure-domains-to-an-existing-nutanix-cluster[Adding failure domains to an existing Nutanix cluster].

* If you deploy using infrastructure that you manage (user-provisioned infrastructure) no additional configuration is required. After the cluster is deployed, you can manually distribute control plane and compute machines across failure domains.
