:_mod-docs-content-type: ASSEMBLY
[id="oadp-introduction"]
= Introduction to {oadp-full}
include::../includes/common-attributes.adoc[]
:context: oadp-api
:namespace: openshift-adp
:local-product: OADP


The {oadp-first} product safeguards customer applications on {product-title}. It offers comprehensive disaster recovery protection, covering {product-title} applications, application-related cluster resources, persistent volumes, and internal images. OADP is also capable of backing up both containerized applications and virtual machines (VMs).

However, OADP does not serve as a disaster recovery solution for xref:backup-etcd[etcd] or OpenShift Operators.


[id="oadp-apis_{context}"]
== {oadp-full} APIs

{oadp-first} provides APIs that enable multiple approaches to customizing backups and preventing the inclusion of unnecessary or inappropriate resources.

OADP provides the following APIs:

* xref:backing-up-applications[Backup]
* xref:restoring-applications[Restore]
* xref:oadp-scheduling-backups-doc[Schedule]
* xref:oadp-about-backup-snapshot-locations_installing-oadp-aws[BackupStorageLocation]
* xref:oadp-backing-up-pvs-csi-doc[VolumeSnapshotLocation]

[role="_additional-resources"]
.Additional resources

* xref:backup-etcd[Backing up etcd]
// once finished re-work come back and add doc links to the APIs

