:_mod-docs-content-type: ASSEMBLY
[id="dist-tracing-jaeger-updating"]
= Updating the distributed tracing platform Jaeger
include::../includes/common-attributes.adoc[]
:context: dist-tracing-jaeger-updating


[WARNING]
====
Jaeger is deprecated in Red Hat OpenShift distributed tracing 3.0.
====

Operator Lifecycle Manager (OLM) controls the installation, upgrade, and role-based access control (RBAC) of Operators in a cluster. The OLM runs by default in {product-title}.
OLM queries for available Operators as well as upgrades for installed Operators.

During an update, the {DTProductName} Operators upgrade the managed {DTShortName} instances to the version associated with the Operator. Whenever a new version of the {JaegerName} Operator is installed, all the {JaegerShortName} application instances managed by the Operator are upgraded to the Operator's version. For example, after upgrading the Operator from 1.10 installed to 1.11, the Operator scans for running {JaegerShortName} instances and upgrades them to 1.11 as well.

[IMPORTANT]
====
If you have not already updated your OpenShift Elasticsearch Operator as described in link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/logging/#cluster-logging-upgrading_cluster-logging-upgrading[Updating OpenShift Logging], complete that update before updating your {JaegerName} Operator.
====

[role="_additional-resources"]
[id="additional-resources_dist-tracing-jaeger-updating"]
== Additional resources

* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/operators/#olm-understanding-olm[Operator Lifecycle Manager concepts and resources]
* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/operators/#olm-upgrading-operators[Updating installed Operators]
* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/logging/#cluster-logging-upgrading_cluster-logging-upgrading[Updating OpenShift Logging]
