:_mod-docs-content-type: ASSEMBLY
[id="about-migrating-from-3-to-4"]
= About migrating from {product-title} 3 to 4
include::includes/common-attributes.adoc[]
:context: about-migrating-from-3-to-4


{product-title} 4 contains new technologies and functionality that result in a cluster that is self-managing, flexible, and automated. {product-title} 4 clusters are deployed and managed very differently from {product-title} 3.

The most effective way to migrate from {product-title} 3 to 4 is by using a CI/CD pipeline to automate deployments in an link:https://www.redhat.com/en/topics/devops/what-is-application-lifecycle-management-alm[application lifecycle management] framework.

If you do not have a CI/CD pipeline or if you are migrating stateful applications, you can use the {mtc-full} ({mtc-short}) to migrate your application workloads.

You can use Red Hat Advanced Cluster Management for Kubernetes to help you import and manage your {product-title} 3 clusters easily, enforce policies, and redeploy your applications. Take advantage of the link:https://www.redhat.com/en/engage/free-access-redhat-e-202202170127[free subscription] to use Red Hat Advanced Cluster Management to simplify your migration process.

To successfully transition to {product-title} 4, review the following information:

xref:planning-migration-3-4[Differences between {product-title} 3 and 4]::
* Architecture
* Installation and upgrade
* Storage, network, logging, security, and monitoring considerations

xref:about-mtc-3-4[About the {mtc-full}]::
* Workflow
* File system and snapshot copy methods for persistent volumes (PVs)
* Direct volume migration
* Direct image migration

xref:advanced-migration-options-3-4[Advanced migration options]::
* Automating your migration with migration hooks
* Using the {mtc-short} API
* Excluding resources from a migration plan
* Configuring the `MigrationController` custom resource for large-scale migrations
* Enabling automatic PV resizing for direct volume migration
* Enabling cached Kubernetes clients for improved performance

For new features and enhancements, technical changes, and known issues, see the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/migration_toolkit_for_containers/#mtc-release-notes[{mtc-short} release notes].
