:_mod-docs-content-type: ASSEMBLY
[id="adding-compute-user-infra-general"]
= Adding compute machines to clusters with user-provisioned infrastructure manually
include::../includes/common-attributes.adoc[]
:context: adding-compute-user-infra-general


You can add compute machines to a cluster on user-provisioned infrastructure either as part of the installation process or after installation. The postinstallation process requires some of the same configuration files and parameters that were used during installation.

[id="upi-adding-compute-aws"]
== Adding compute machines to Amazon Web Services

To add more compute machines to your {product-title} cluster on Amazon Web Services (AWS), see xref:adding-aws-compute-user-infra[Adding compute machines to AWS by using CloudFormation templates].

[id="upi-adding-compute-azure"]
== Adding compute machines to Microsoft Azure

To add more compute machines to your {product-title} cluster on Microsoft Azure, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/installing/#installation-creating-azure-worker_installing-azure-user-infra[Creating additional worker machines in Azure].

[id="upi-adding-compute-ash"]
== Adding compute machines to Azure Stack Hub

To add more compute machines to your {product-title} cluster on Azure Stack Hub, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/installing/#installation-creating-azure-worker_installing-azure-stack-hub-user-infra[Creating additional worker machines in Azure Stack Hub].

[id="upi-adding-compute-gcp"]
== Adding compute machines to Google Cloud Platform

To add more compute machines to your {product-title} cluster on Google Cloud Platform (GCP), see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/installing/#installation-creating-gcp-worker_installing-restricted-networks-gcp[Creating additional worker machines in GCP].

[id="upi-adding-compute-vsphere"]
== Adding compute machines to vSphere

You can xref:creating-machineset-vsphere[use compute machine sets] to automate the creation of additional compute machines for your {product-title} cluster on vSphere.

To manually add more compute machines to your cluster, see xref:adding-vsphere-compute-user-infra[Adding compute machines to vSphere manually].


[id="upi-adding-compute-bare-metal"]
== Adding compute machines to bare metal

To add more compute machines to your {product-title} cluster on bare metal, see xref:adding-bare-metal-compute-user-infra[Adding compute machines to bare metal].
