:_mod-docs-content-type: ASSEMBLY
[id="compliance-operator-installation"]
= Installing the Compliance Operator
include::../../includes/common-attributes.adoc[]
:context: compliance-operator-installation


Before you can use the Compliance Operator, you must ensure it is deployed in the cluster.

[IMPORTANT]
====
The Compliance Operator might report incorrect results on managed platforms, such as OpenShift Dedicated, Red Hat OpenShift Service on AWS, and Microsoft Azure Red Hat OpenShift. For more information, see the link:https://access.redhat.com/solutions/6983418[Red Hat Knowledgebase Solution #6983418].
====

include::../../includes/compliance-operator-console-installation.adoc[leveloffset=+1]

[IMPORTANT]
====
If the `restricted` Security Context Constraints (SCC) have been modified to contain the `system:authenticated` group or has added `requiredDropCapabilities`, the Compliance Operator may not function properly due to permissions issues.

You can create a custom SCC for the Compliance Operator scanner pod service account. For more information, see xref:compliance-custom-scc_compliance-advanced[Creating a custom SCC for the Compliance Operator].
====

include::../../includes/compliance-operator-cli-installation.adoc[leveloffset=+1]

[IMPORTANT]
====
If the `restricted` Security Context Constraints (SCC) have been modified to contain the `system:authenticated` group or has added `requiredDropCapabilities`, the Compliance Operator may not function properly due to permissions issues.

You can create a custom SCC for the Compliance Operator scanner pod service account. For more information, see xref:compliance-custom-scc_compliance-advanced[Creating a custom SCC for the Compliance Operator].
====

// only applies to 4.11+
include::../../includes/compliance-operator-hcp-install.adoc[leveloffset=+1]

[role="_additional-resources"]
.Additional resources

// 4.13+
* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/hosted_control_planes/#hcp-overview[Hosted control planes overview]
//
// 4.11-4.12, commenting out of 4.13-main
//* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/architecture/#hosted-control-planes-overview_control-plane[Overview of hosted control planes (Technology Preview)]

[id="additional-resources-installing-the-compliance-operator"]
[role="_additional-resources"]
== Additional resources

* The Compliance Operator is supported in a restricted network environment. For more information, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/operators/#olm-restricted-networks[Using Operator Lifecycle Manager on restricted networks].
