:_mod-docs-content-type: ASSEMBLY
[id="service-mesh-release-notes-v1x"]
= Service Mesh Release Notes
include::../includes/common-attributes.adoc[]
:context: ossm-release-notes-v1x


include::../includes/ossm-out-of-support.adoc[]

== Making open source more inclusive

Red Hat is committed to replacing problematic language in our code, documentation, and web properties. We are beginning with these four terms: master, slave, blacklist, and whitelist. Because of the enormity of this endeavor, these changes will be implemented gradually over several upcoming releases. For more details, see link:https://www.redhat.com/en/blog/making-open-source-more-inclusive-eradicating-problematic-language[our CTO Chris Wright's message].


// The following include statements pull in the module files that comprise 1.x release notes.

include::../includes/ossm-servicemesh-overview.adoc[leveloffset=+1]

include::../includes/support.adoc[leveloffset=+1]

When opening a support case, it is helpful to provide debugging
information about your cluster to Red Hat Support.

The `must-gather` tool enables you to collect diagnostic information about your
{product-title} cluster, including virtual machines and other data related to
{SMProductName}.

For prompt support, supply diagnostic information for both {product-title}
and {SMProductName}.

include::../includes/about-must-gather.adoc[leveloffset=+2]

=== Prerequisites

* Access to the cluster as a user with the `cluster-admin` role.

* The {product-title} CLI (`oc`) installed.

include::../includes/ossm-about-collecting-ossm-data.adoc[leveloffset=+2]

include::../includes/ossm-supported-configurations-v1x.adoc[leveloffset=+1]

include::../includes/ossm-rn-new-features-1x.adoc[leveloffset=+1]

include::../includes/ossm-rn-deprecated-features-1x.adoc[leveloffset=+1]

include::../includes/ossm-rn-known-issues-1x.adoc[leveloffset=+1]

include::../includes/ossm-rn-fixed-issues-1x.adoc[leveloffset=+1]
