:_mod-docs-content-type: ASSEMBLY
[id="backing-up-applications"]
= Backing up applications
include::../../includes/common-attributes.adoc[]
include::../../includes/attributes-openshift-dedicated.adoc[]
:context: backing-up-applications


You back up applications by creating a `Backup` custom resource (CR). See xref:oadp-creating-backup-cr-doc[Creating a Backup CR].

* The `Backup` CR creates backup files for Kubernetes resources and internal images on S3 object storage.
* If your cloud provider has a native snapshot API or supports CSI snapshots, the `Backup` CR backs up persistent volumes (PVs) by creating snapshots. For more information about working with CSI snapshots, see xref:oadp-backing-up-pvs-csi-doc[Backing up persistent volumes with CSI snapshots].

For more information about CSI volume snapshots, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/storage/#persistent-storage-csi-snapshots[CSI volume snapshots].

:FeatureName: The `CloudStorage` API, which automates the creation of a bucket for object storage,
include::../../includes/technology-preview.adoc[]

[NOTE]
====
The `CloudStorage` API is a Technology Preview feature when you use a `CloudStorage` object and want OADP to use the `CloudStorage` API to automatically create an S3 bucket for use as a `BackupStorageLocation`.

The `CloudStorage` API supports manually creating a `BackupStorageLocation` object by specifying an existing S3 bucket. The `CloudStorage` API that creates an S3 bucket automatically is currently only enabled for AWS S3 storage.
====

* If your cloud provider does not support snapshots or if your applications are on NFS data volumes, you can create backups by using Kopia or Restic. See xref:oadp-backing-up-applications-restic-doc[Backing up applications with File System Backup: Kopia or Restic].

[IMPORTANT]
====
The {oadp-first} does not support backing up volume snapshots that were created by other software.
====

You can create backup hooks to run commands before or after the backup operation. See xref:oadp-creating-backup-hooks-doc[Creating backup hooks].

You can schedule backups by creating a `Schedule` CR instead of a `Backup` CR. See xref:oadp-scheduling-backups-doc[Scheduling backups using Schedule CR]].

// include::../../includes/oadp-creating-backup-cr.adoc[leveloffset=+1]
// include::../../includes/oadp-backing-up-pvs-csi.adoc[leveloffset=+1]
// include::../../includes/oadp-backing-up-applications-restic.adoc[leveloffset=+1]

[id="known-issues-backing-up-applications"]
== Known issues

{ocp} {product-version} enforces a pod security admission (PSA) policy that can hinder the readiness of pods during a Restic restore process. 

This issue has been resolved in the OADP 1.1.6 and OADP 1.2.2 releases, therefore it is recommended that users upgrade to these releases.

For more information, see xref:oadp-restic-restore-failing-psa-policy_oadp-troubleshooting[Restic restore partially failing on OCP 4.15 due to changed PSA policy].

[role="_additional-resources"]
.Additional resources
* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/operators/#olm-installing-operators-from-operatorhub_olm-adding-operators-to-a-cluster[Installing Operators on clusters for administrators]
* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/operators/#olm-installing-operators-in-namespace[Installing Operators in namespaces for non-administrators]



