:_mod-docs-content-type: ASSEMBLY
[id="security-compliance-overview"]
= {product-title} security and compliance
include::includes/common-attributes.adoc[]
:context: security-compliance-overview


// TODO: Need some help with an intro blurb

[id="security-overview"]
== Security overview

It is important to understand how to properly secure various aspects of your {product-title} cluster.

[discrete]
[id="container-security"]
=== Container security

A good starting point to understanding {product-title} security is to review the concepts in xref:security-understanding[Understanding container security]. This and subsequent sections provide a high-level walkthrough of the container security measures available in {product-title}, including solutions for the host layer, the container and orchestration layer, and the build and application layer. These sections also include information on the following topics:

* Why container security is important and how it compares with existing security standards.
* Which container security measures are provided by the host ({op-system} and {op-system-base}) layer and
which are provided by {product-title}.
* How to evaluate your container content and sources for vulnerabilities.
* How to design your build and deployment process to proactively check container content.
* How to control access to containers through authentication and authorization.
* How networking and attached storage are secured in {product-title}.
* Containerized solutions for API management and SSO.

[discrete]
[id="auditing"]
=== Auditing

{product-title} auditing provides a security-relevant chronological set of records documenting the sequence of activities that have affected the system by individual users, administrators, or other components of the system. Administrators can xref:audit-log-policy-config[configure the audit log policy] and xref:audit-log-view[view audit logs].

[discrete]
[id="certificates"]
=== Certificates

Certificates are used by various components to validate access to the cluster. Administrators can xref:replacing-default-ingress[replace the default ingress certificate], xref:api-server-certificates[add API server certificates], or xref:add-service-serving[add a service certificate].

You can also review more details about the types of certificates used by the cluster:

// TODO: there isn't a cert description landing page. Consider adding one instead of all of these links?
* xref:cert-types-user-provided-certificates-for-the-api-server[User-provided certificates for the API server]
* xref:cert-types-proxy-certificates[Proxy certificates]
* xref:cert-types-service-ca-certificates[Service CA certificates]
* xref:cert-types-node-certificates[Node certificates]
* xref:cert-types-bootstrap-certificates[Bootstrap certificates]
* xref:cert-types-etcd-certificates[etcd certificates]
* xref:cert-types-olm-certificates[OLM certificates]
* xref:cert-types-aggregated-api-client-certificates[Aggregated API client certificates]
* xref:cert-types-machine-config-operator-certificates[Machine Config Operator certificates]
* xref:cert-types-user-provided-certificates-for-default-ingress[User-provided certificates for default ingress]
* xref:cert-types-ingress-certificates[Ingress certificates]
* xref:cert-types-monitoring-and-cluster-logging-operator-component-certificates[Monitoring and cluster logging Operator component certificates]
* xref:cert-types-control-plane-certificates[Control plane certificates]

[discrete]
[id="encrypting-data"]
=== Encrypting data

You can xref:encrypting-etcd[enable etcd encryption] for your cluster to provide an additional layer of data security. For example, it can help protect the loss of sensitive data if an etcd backup is exposed to the incorrect parties.

[discrete]
[id="vulnerability-scanning"]
=== Vulnerability scanning

Administrators can use the {rhq-cso} to run xref:pod-vulnerability-scan[vulnerability scans] and review information about detected vulnerabilities.

[id="compliance-overview"]
== Compliance overview

For many {product-title} customers, regulatory readiness, or compliance, on some level is required before any systems can be put into production. That regulatory readiness can be imposed by national standards, industry standards, or the organization's corporate governance framework.

[discrete]
[id="compliance-checking"]
=== Compliance checking

Administrators can use the xref:understanding-compliance-operator[Compliance Operator] to run compliance scans and recommend remediations for any issues found. The xref:using-oc-compliance-plug-in[`oc-compliance` plugin] is an OpenShift CLI (`oc`) plugin that provides a set of utilities to easily interact with the Compliance Operator.

[discrete]
[id="file-integrity-checking"]
=== File integrity checking

Administrators can use the xref:understanding-file-integrity-operator[File Integrity Operator] to continually run file integrity checks on cluster nodes and provide a log of files that have been modified.

[id="additional-resources_security-compliance-overview"]
[role="_additional-resources"]
== Additional resources

* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/authentication_and_authorization/#understanding-authentication[Understanding authentication]
* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/authentication_and_authorization/#configuring-internal-oauth[Configuring the internal OAuth server]
* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/authentication_and_authorization/#understanding-identity-provider[Understanding identity provider configuration]
* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/authentication_and_authorization/#using-rbac[Using RBAC to define and apply permissions]
* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/authentication_and_authorization/#managing-pod-security-policies[Managing security context constraints]
