:_mod-docs-content-type: ASSEMBLY
include::../includes/common-attributes.adoc[]
[id="installing-virt"]
= Installing {VirtProductName}
:context: installing-virt


Install {VirtProductName} to add virtualization functionality to your {product-title} cluster.

[IMPORTANT]
====
If you install {VirtProductName} in a restricted environment with no internet connectivity, you must link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/operators/#olm-restricted-networks[configure Operator Lifecycle Manager (OLM) for restricted networks].

If you have limited internet connectivity, you can link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/operators/#olm-configuring-proxy-support[configure proxy support in OLM] to access the OperatorHub.
====

[id="installing-virt-operator_installing-virt"]
== Installing the {VirtProductName} Operator

Install the {VirtProductName} Operator by using the {product-title} web console or the command line.

include::../includes/virt-installing-virt-operator.adoc[leveloffset=+2]

[id="installing-virt-operator-cli_installing-virt"]
=== Installing the {VirtProductName} Operator by using the command line

Subscribe to the {VirtProductName} catalog and install the {VirtProductName} Operator by applying manifests to your cluster.

include::../includes/virt-subscribing-cli.adoc[leveloffset=+3]

[NOTE]
====
You can xref:virt-configuring-certificate-rotation[configure certificate rotation] parameters in the YAML file.
====

include::../includes/virt-deploying-operator-cli.adoc[leveloffset=+3]

[id="installing-virt-web-next-steps"]
== Next steps

* The xref:virt-creating-hpp-basic-storage-pool_virt-configuring-local-storage-with-hpp[hostpath provisioner] is a local storage provisioner designed for {VirtProductName}. If you want to configure local storage for virtual machines, you must enable the hostpath provisioner first.
