:_mod-docs-content-type: ASSEMBLY
[id="spo-overview"]
= Security Profiles Operator overview
include::../includes/common-attributes.adoc[]
:context: spo-overview

{product-title} Security Profiles Operator (SPO) provides a way to define secure computing (https://kubernetes.io/docs/tutorials/security/seccomp/[seccomp]) profiles and SELinux profiles as custom resources, synchronizing profiles to every node in a given namespace. For the latest updates, see the xref:spo-release-notes[release notes].

The SPO can distribute custom resources to each node while a reconciliation loop ensures that the profiles stay up-to-date. See xref:spo-understanding[Understanding the Security Profiles Operator].

The SPO manages SELinux policies and seccomp profiles for namespaced workloads. For more information, see xref:spo-enabling[Enabling the Security Profiles Operator].

You can create xref:spo-seccomp[seccomp] and xref:spo-selinux[SELinux] profiles, bind policies to pods, record workloads, and synchronize all worker nodes in a namespace.

Use xref:spo-advanced[Advanced Security Profile Operator tasks] to enable the log enricher, configure webhooks and metrics, or restrict profiles to a single namespace.

xref:[Troubleshoot the Security Profiles Operator] as needed, or engage link:https://access.redhat.com/support/[Red Hat support].

You can xref:spo-uninstalling[Uninstall the Security Profiles Operator] by removing the profiles before removing the Operator.
