:_mod-docs-content-type: ASSEMBLY
include::../includes/common-attributes.adoc[]
[id="virt-backing-up-vms"]
= Backing up virtual machines
:context: virt-backing-up-vms


You back up virtual machines (VMs) by creating an OpenShift API for Data Protection (OADP) xref:oadp-creating-backup-cr_virt-backing-up-vms[`Backup` custom resource (CR)].

The `Backup` CR performs the following actions:

* Backs up {VirtProductName} resources by creating an archive file on S3-compatible object storage, such as link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/backup_and_restore/#installing-oadp-mcg[Multicloud Object Gateway], Noobaa, or Minio.
* Backs up VM disks by using one of the following options:

** xref:oadp-backing-up-pvs-csi_virt-backing-up-vms[Container Storage Interface (CSI) snapshots] on CSI-enabled cloud storage, such as Ceph RBD or Ceph FS.
** link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/backup_and_restore/#backing-up-applications[Backing up applications with File System Backup: Kopia or Restic] on object storage.

[NOTE]
====
OADP provides backup hooks to freeze the VM file system before the backup operation and unfreeze it when the backup is complete.

The `kubevirt-controller` creates the `virt-launcher` pods with annotations that enable Velero to run the `virt-freezer` binary before and after the backup operation.

The `freeze` and `unfreeze` APIs are subresources of the VM snapshot API. See xref:virt-about-vm-snapshots_virt-backup-restore-snapshots[About virtual machine snapshots] for details.
====

You can add link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/backup_and_restore/#backing-up-applications[hooks] to the `Backup` CR to run commands on specific VMs before or after the backup operation.

You schedule a backup by creating a link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/backup_and_restore/#backing-up-applications[`Schedule` CR] instead of a `Backup` CR.

include::../includes/oadp-creating-backup-cr.adoc[leveloffset=+1]
include::../includes/oadp-backing-up-pvs-csi.adoc[leveloffset=+2]
include::../includes/oadp-backing-up-applications-restic.adoc[leveloffset=+2]
include::../includes/oadp-creating-backup-hooks.adoc[leveloffset=+2]

[id="additional-resources_virt-backing-up-vms"]
== Additional resources

* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/storage/#persistent-storage-csi-snapshots-overview_persistent-storage-csi-snapshots[Overview of CSI volume snapshots]
