:_mod-docs-content-type: ASSEMBLY
[id="configuring-custom-helm-chart-repositories"]
= Configuring custom Helm chart repositories
include::../includes/common-attributes.adoc[]
:context: configuring-custom-helm-chart-repositories


[role="_abstract"]
You can create Helm releases on an {product-title} cluster using the following methods:

* The CLI.
* The *Developer* perspective of the web console.

The *Developer Catalog*, in the *Developer* perspective of the web console, displays the Helm charts available in the cluster. By default, it lists the Helm charts from the Red Hat OpenShift Helm chart repository. For a list of the charts, see link:https://charts.openshift.io/index.yaml[the Red Hat `Helm index` file].

As a cluster administrator, you can add multiple cluster-scoped and namespace-scoped Helm chart repositories, separate from the default cluster-scoped Helm repository, and display the Helm charts from these repositories in the *Developer Catalog*.

As a regular user or project member with the appropriate role-based access control (RBAC) permissions, you can add multiple namespace-scoped Helm chart repositories, apart from the default cluster-scoped Helm repository, and display the Helm charts from these repositories in the *Developer Catalog*.

In the *Developer* perspective of the web console, you can use the *Helm* page to:

* Create Helm Releases and Repositories using the *Create* button.

* Create, update, or delete a cluster-scoped or namespace-scoped Helm chart repository.

* View the list of the existing Helm chart repositories in the Repositories tab, which can also be easily distinguished as either cluster scoped or namespace scoped.

include::../includes/helm-installing-a-helm-chart-on-an-openshift-cluster.adoc[leveloffset=+1]

include::../includes/odc-creating-helm-releases-using-developer-perspective.adoc[leveloffset=+1]

== Using Helm in the web terminal

You can use Helm by link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/web_console/#odc-access-web-terminal_odc-using-web-terminal[Accessing the web terminal] in the *Developer* perspective of the web console.

include::../includes/helm-creating-a-custom-helm-chart-on-openshift.adoc[leveloffset=+1]

include::../includes/helm-adding-helm-chart-repositories.adoc[leveloffset=+1]

include::../includes/helm-adding-namespace-scoped-helm-chart-repositories.adoc[leveloffset=+1]

include::../includes/helm-creating-credentials-and-certificates-to-add-helm-repositories.adoc[leveloffset=+1]

include::../includes/helm-filtering-helm-charts-by-certification-level.adoc[leveloffset=+1]

include::../includes/helm-disabling-helm-chart-repositories.adoc[leveloffset=+1]
