:_mod-docs-content-type: ASSEMBLY
[id="about-mtc"]
= About the Migration Toolkit for Containers
include::includes/common-attributes.adoc[]
:context: about-mtc


The {mtc-full} ({mtc-short}) enables you to migrate stateful application workloads between {product-title} 4 clusters at the granularity of a namespace.

[NOTE]
====
If you are migrating from {product-title} 3, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/migrating_from_version_3_to_4/#about-migrating-from-3-to-4[About migrating from {product-title} 3 to 4] and link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/migrating_from_version_3_to_4/#migration-installing-legacy-operator_installing-3-4[Installing the legacy {mtc-full} Operator on {product-title} 3].
====

You can migrate applications within the same cluster or between clusters by using state migration.

{mtc-short} provides a web console and an API, based on Kubernetes custom resources, to help you control the migration and minimize application downtime.

The {mtc-short} console is installed on the target cluster by default. You can configure the {mtc-full} Operator to install the console on a link:https://access.redhat.com/articles/5064151[remote cluster].

See xref:advanced-migration-options-mtc[Advanced migration options] for information about the following topics:

* Automating your migration with migration hooks and the {mtc-short} API.
* Configuring your migration plan to exclude resources, support large-scale migrations, and enable automatic PV resizing for direct volume migration.

include::includes/migration-terminology.adoc[leveloffset=+1]
include::includes/migration-mtc-workflow.adoc[leveloffset=+1]
include::includes/migration-understanding-data-copy-methods.adoc[leveloffset=+1]
include::includes/migration-direct-volume-migration-and-direct-image-migration.adoc[leveloffset=+1]
